import Link from "next/link";
import { requireUser } from "@/lib/auth/session";
import { careerReadiness, getIdentityWorkspace, profileCompletion } from "@/lib/identity/repository";
import { ProgressMeter } from "@/components/identity/ProgressMeter";
import { ResumeUploader } from "@/components/identity/ResumeUploader";

function Card({ title, id, children }: { title: string; id?: string; children: React.ReactNode }) { return <section id={id} className="glass rounded-2xl border border-white/[.07] p-6"><h2 className="text-sm font-semibold text-white">{title}</h2><div className="mt-5">{children}</div></section>; }
export default async function DashboardPage() {
  const user = await requireUser(); const data = await getIdentityWorkspace(user);
  const completion = profileCompletion(data.profile); const readiness = careerReadiness(data.profile, data.resumes.length > 0, Boolean(data.preferences?.job_search_region));
  return <main className="mx-auto max-w-6xl px-5 py-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Career command center</p><h1 className="mt-2 font-display text-3xl font-semibold text-white">Welcome{data.profile.name ? `, ${data.profile.name.split(" ")[0]}` : " to your Career OS"}</h1><p className="mt-2 text-sm text-slate-400">A focused view of your identity, readiness, and next actions.</p></div><Link href="/profile" className="btn-secondary min-h-11 text-sm">Edit profile</Link></div>
    <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><Card title="Profile completion"><ProgressMeter value={completion} label={completion === 100 ? "Profile complete" : "Strengthen your career identity"} /></Card><Card title="Career readiness"><ProgressMeter value={readiness} label={readiness >= 80 ? "Ready for focused action" : "Build the foundations"} /></Card><Card title="Subscription"><p className="text-2xl font-semibold capitalize text-white">{data.subscription?.plan ?? "free"}</p><p className="mt-2 text-sm text-slate-500">Your current Career OS plan</p></Card>
      <Card title="Saved careers"><p className="text-3xl font-semibold text-white">{data.savedCareers.length}</p><p className="mt-2 text-sm leading-6 text-slate-500">{data.savedCareers.length ? data.savedCareers.slice(0, 3).map((career) => career.career_slug.replaceAll("-", " ")).join(" · ") : "Bookmark promising directions from any career workspace."}</p><Link href="/#career-universe" className="mt-4 inline-block text-sm text-indigo-300">Explore careers →</Link></Card>
      <Card title="Resumes" id="resumes"><div className="flex items-start justify-between gap-4"><div><p className="text-3xl font-semibold text-white">{data.resumes.length}</p><p className="mt-2 text-sm text-slate-500">{data.resumes[0] ? `Latest: ${data.resumes[0].title}` : "Your private resume library is ready."}</p></div><ResumeUploader userId={user.id} /></div>{data.resumes.length > 1 ? <ul className="mt-4 space-y-2 border-t border-white/[.06] pt-4">{data.resumes.slice(0, 3).map((resume) => <li key={resume.id} className="flex justify-between text-xs"><span className="text-slate-300">{resume.title}</span><span className="uppercase text-slate-600">{resume.file_type} · v{resume.version}</span></li>)}</ul> : null}</Card>
      <Card title="Recent activity">{data.activity.length ? <ul className="space-y-3">{data.activity.slice(0, 5).map((activity) => <li key={activity.id} className="flex justify-between gap-4 text-sm"><span className="capitalize text-slate-300">{activity.action.replaceAll("_", " ")}</span><time className="text-xs text-slate-600">{new Date(activity.created_at).toLocaleDateString()}</time></li>)}</ul> : <p className="text-sm leading-6 text-slate-500">Your milestones will appear here as you build momentum.</p>}</Card></div>
  </main>;
}

