import "server-only";
import { freshnessDays,type SnapshotType } from "@/lib/intelligence/snapshotRegistry";
export interface PublishedSnapshot {id:string;career_slug:string;country_code:string;snapshot_type:SnapshotType;provider:string;status:"published";version:number;query_metadata:Record<string,unknown>;normalized_payload:Record<string,unknown>;sample_size:number;total_count:number|null;currency_code:string|null;captured_at:string;published_at:string;validation_result:Record<string,unknown>}
function database(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;return url&&key?{url,key}:null}
async function dbFetch(path:string,init:RequestInit={}){const db=database();if(!db)throw new Error("SNAPSHOT_DATABASE_NOT_CONFIGURED");const response=await fetch(`${db.url}/rest/v1/${path}`,{...init,headers:{apikey:db.key,"Content-Type":"application/json",Prefer:"return=representation",...init.headers},cache:"no-store"});if(!response.ok)throw new Error(`SNAPSHOT_DATABASE_${response.status}`);return response.json()}
export async function latestPublished(career:string,country:string,type:SnapshotType):Promise<PublishedSnapshot|null>{const rows=await dbFetch(`intelligence_snapshots?career_slug=eq.${encodeURIComponent(career)}&country_code=eq.${country}&snapshot_type=eq.${type}&status=eq.published&order=published_at.desc&limit=1&select=*`) as PublishedSnapshot[];return rows[0]??null}
export async function snapshotView(career:string,country:string,type:SnapshotType){const snapshot=await latestPublished(career,country,type);if(!snapshot)return {availability:"no-verified-data" as const,message:"No verified snapshot is available."};const age=Date.now()-Date.parse(snapshot.captured_at),stale=age>freshnessDays(type)*86400000;return {availability:stale?"stale":"fresh",freshness:stale?"Stale":`Updated ${Math.max(0,Math.floor(age/86400000))} days ago`,schedule:type==="market"?"Weekly snapshot":"Monthly snapshot",snapshot}}
export async function createRun(body:Record<string,unknown>){const rows=await dbFetch("intelligence_refresh_runs",{method:"POST",body:JSON.stringify(body)}) as Array<{id:string}>;return rows[0]}
export async function updateRun(id:string,body:Record<string,unknown>){return dbFetch(`intelligence_refresh_runs?id=eq.${id}`,{method:"PATCH",body:JSON.stringify(body)})}
export async function createItem(body:Record<string,unknown>){const rows=await dbFetch("intelligence_refresh_items",{method:"POST",body:JSON.stringify(body)}) as Array<{id:string}>;return rows[0]}
export async function updateItem(id:string,body:Record<string,unknown>){return dbFetch(`intelligence_refresh_items?id=eq.${id}`,{method:"PATCH",body:JSON.stringify(body)})}
export async function saveAndPublish(body:Record<string,unknown>){const rows=await dbFetch("intelligence_snapshots",{method:"POST",body:JSON.stringify({...body,status:"draft"})}) as Array<{id:string}>;const id=rows[0].id;await dbFetch(`intelligence_snapshots?id=eq.${id}&status=eq.draft`,{method:"PATCH",body:JSON.stringify({status:"validating"})});return dbFetch("rpc/publish_intelligence_snapshot",{method:"POST",body:JSON.stringify({snapshot_id:id})})}
export function databaseConfigured(){return Boolean(database())}
