import Link from "next/link";
import { notFound } from "next/navigation";
import CareerForm from "@/components/admin/CareerForm";
import ArchiveCareerControl from "@/components/admin/ArchiveCareerControl";
import { publishCareerAction, unpublishCareerAction, updateCareerAction } from "@/app/admin/(studio)/careers/actions";
import { requireAdmin } from "@/lib/admin/adminAuth";
import { getCareer, listAudit } from "@/lib/admin/careerRepository";
import { evaluateCareerCompletion } from "@/lib/admin/careerStudio";

export default async function EditCareerPage({ params, searchParams }: { params:Promise<{id:string}>; searchParams:Promise<{saved?:string;error?:string}> }) {
  const authorization = await requireAdmin(); if (authorization.status !== "admin") return null;
  const {id} = await params, [career,audit] = await Promise.all([getCareer(authorization.accessToken,id),listAudit(authorization.accessToken,id,20)]); if(!career) notFound();
  const query = await searchParams, ready = Boolean(career.workspace_data) && !(career.validation_errors?.length);
  const evaluation = evaluateCareerCompletion(career.workspace_data,{status:career.status,validationErrors:career.validation_errors});
  const { completion } = evaluation, missing = evaluation.sections.filter((item)=>item.state==="missing"||item.state==="error");
  const canPublish = ready && ["ready","ready-with-warnings"].includes(evaluation.readiness);
  const lastManual = audit.find((entry)=>entry.action === "career.content_updated" || entry.action === "career.updated");
  return <main className="p-4 sm:p-8"><Link href="/admin/careers" className="text-sm text-cyan-300 underline">← Career catalog</Link>
    <div className="mt-5 flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">Career workspace</p><h2 className="mt-2 font-display text-3xl font-semibold text-white">{career.title}</h2><p className="mt-2 text-sm text-slate-400">/{career.slug} · Draft v{career.content_version} · Updated {new Date(career.updated_at).toLocaleString()}</p></div><div className="flex flex-wrap gap-2"><Link href={`/admin/careers/${id}/preview`} aria-disabled={!career.workspace_data} className={`btn-secondary min-h-11 ${career.workspace_data ? "" : "pointer-events-none opacity-40"}`}>Preview</Link><Link href={`/admin/careers/new?duplicate=${id}`} className="btn-secondary min-h-11">Duplicate</Link><ArchiveCareerControl id={career.id} archived={career.status === "archived"}/></div></div>
    {query.saved ? <p role="status" className="mt-5 rounded-xl bg-emerald-400/10 p-3 text-sm text-emerald-200">Career {query.saved} successfully.</p> : null}{query.error ? <p role="alert" className="mt-5 rounded-xl bg-rose-400/10 p-3 text-sm text-rose-200">The requested state change could not be completed.</p> : null}
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Career status" value={career.status}/><Metric label="Completion score" value={`${completion}%`}/><Metric label="Publication readiness" value={evaluation.readiness.replace(/-/g," ")}/><Metric label="Missing sections" value={missing.length ? String(missing.length) : "None"}/><Metric label="Published version" value={career.published_at ? `v${career.content_version}` : "Never"}/><Metric label="Draft version" value={`v${career.content_version}`}/><Metric label="Last manual edit" value={lastManual ? new Date(lastManual.created_at).toLocaleDateString() : "No record"}/><Metric label="Last AI update" value="No AI draft"/></section>
    <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h3 className="font-semibold text-white">Content workflow</h3><p className="mt-1 text-sm text-slate-400">AI Generated → Preview → Approved → Published. Publication always requires an administrator action.</p></div><div className="flex gap-2"><Link href={`/admin/careers/${id}/content`} className="btn-primary min-h-11">Open Content Studio</Link>{career.status === "published" ? <form action={unpublishCareerAction}><input type="hidden" name="id" value={id}/><button className="btn-secondary min-h-11">Unpublish</button></form> : <form action={publishCareerAction}><input type="hidden" name="id" value={id}/><button disabled={!canPublish || career.status === "archived"} title={!canPublish?"Resolve publication blockers before publishing.":undefined} className="btn-secondary min-h-11 disabled:cursor-not-allowed disabled:opacity-40">Approve & publish</button></form>}</div></div><div className="mt-5 grid gap-2 sm:grid-cols-5">{["Draft","AI Generated","Preview","Approved","Published"].map((step,index)=><div key={step} className={`rounded-xl border p-3 text-center text-xs font-semibold ${index === 0 || (career.status === "published" && index === 4) ? "border-indigo-400/30 bg-indigo-400/10 text-indigo-100" : "border-white/10 text-slate-500"}`}>{step}</div>)}</div></section>
    {evaluation.blockers.length ? <section className="mt-6 rounded-2xl border border-amber-300/15 bg-amber-300/[.04] p-5"><h3 className="font-semibold text-amber-100">{evaluation.readiness==="not-ready"?"Not ready to publish":"Readiness warnings"}</h3><p className="mt-1 text-sm text-amber-100/70">Resolve required blockers before publication. Each item opens the relevant editor.</p><ul className="mt-3 grid gap-2 md:grid-cols-2">{evaluation.blockers.map((item,index)=><li key={`${item.section}-${index}`}><Link href={`/admin/careers/${id}/content?section=${item.section}`} className="flex min-h-11 items-center justify-between rounded-lg border border-amber-300/15 px-3 py-2 text-xs text-amber-100"><span>{item.message}</span><span className="ml-3 shrink-0 uppercase text-amber-200/60">{item.severity}</span></Link></li>)}</ul></section> : null}
    <details className="mt-6 max-w-5xl rounded-2xl border border-white/10 bg-white/[.025] p-5"><summary className="cursor-pointer font-semibold text-white">Career identity and taxonomy</summary><div className="mt-5"><CareerForm action={updateCareerAction} career={career}/></div></details>
    <section className="mt-6 max-w-5xl rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold text-white">Version history</h3><p className="mt-1 text-xs text-slate-500">Every saved content version and state transition is retained in the audit timeline.</p></div><span className="text-xs text-slate-500">{audit.length} recent events</span></div>{audit.length ? <ol className="mt-4 divide-y divide-white/10">{audit.map((entry)=><li key={entry.id} className="grid gap-2 py-3 text-sm sm:grid-cols-[1fr_auto]"><div><span className="font-medium text-slate-200">{entry.action.replace("career.","").replace(/_/g," ")}</span><span className="ml-2 text-slate-500">{(entry.changed_fields.fields ?? []).join(", ")}</span></div><time className="text-xs text-slate-500">{new Date(entry.created_at).toLocaleString()}</time></li>)}</ol> : <p className="mt-4 text-sm text-slate-500">No version activity is available.</p>}</section>
  </main>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 truncate text-lg font-semibold capitalize text-white">{value}</p></div>}
