import AIWorkspaceGuestCodeForm from "@/components/admin/AIWorkspaceGuestCodeForm";
import { createServiceClient } from "@/lib/supabase/admin";
import { adjustCreditAction, reconcileUncertainAction, revokeGuestCodeAction, revokeGuestDeviceAction, setModelEnabledAction } from "./actions";

export const dynamic = "force-dynamic";

function usd(value: unknown) {
  try { return `$${(Number(BigInt(String(value ?? 0))) / 1_000_000).toFixed(4)}`; } catch { return "—"; }
}
function when(value: string | null | undefined) {
  return value ? new Date(value).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" }) : "—";
}

export default async function AIWorkspaceAdminPage() {
  const service = createServiceClient();
  const [accounts, codes, devices, uncertain, models, plans, plugins, audit] = await Promise.all([
    service.from("aiw_accounts").select("id,user_id,kind,status,daily_limit,monthly_limit,plan_key,expires_at,created_at").order("created_at", { ascending: false }).limit(100),
    service.from("aiw_guest_codes").select("id,label,status,expires_at,max_activations,activation_count,device_limit,initial_credit,daily_limit,monthly_limit,created_at").order("created_at", { ascending: false }).limit(100),
    service.from("aiw_guest_devices").select("id,owner_id,revoked,expires_at,created_at").order("created_at", { ascending: false }).limit(100),
    service.from("aiw_requests").select("id,owner_id,request_kind,reserved_micros,error_code,provider_state,created_at,uncertain_at").eq("status", "uncertain").order("created_at", { ascending: false }).limit(100),
    service.from("aiw_models").select("id,config,updated_at").order("id"),
    service.from("aiw_plan_entitlements").select("plan_key,config,active,updated_at").order("plan_key"),
    service.from("aiw_plugin_catalog").select("id,display_name,status,auth_kind,capabilities,updated_at").order("display_name"),
    service.from("aiw_audit").select("id,actor_id,owner_id,action,details,created_at").order("created_at", { ascending: false }).limit(40),
  ]);
  const errors = [accounts,codes,devices,uncertain,models,plans,plugins,audit].flatMap(result => result.error ? [result.error.message] : []);
  const activeModels = (models.data ?? []).filter(row => (row.config as { enabled?: boolean })?.enabled === true && !row.id.startsWith("test-")).map(row => row.id);

  return <main className="mx-auto max-w-[1500px] px-4 py-8 sm:px-8">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-violet-300">AI operations</p><h1 className="mt-2 font-display text-3xl font-semibold text-white">AI Control Center</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Operational control for guest access, account credit, uncertain cost reconciliation, provider models, plans, plugins and audit. Conversation content is not exposed in this dashboard.</p></div><div className="flex flex-wrap gap-2 text-xs"><Metric label="Accounts" value={accounts.data?.length ?? 0} /><Metric label="Guest codes" value={codes.data?.length ?? 0} /><Metric label="Uncertain" value={uncertain.data?.length ?? 0} /></div></div>
    {errors.length ? <div className="mt-5 rounded-xl border border-rose-300/20 bg-rose-400/[.07] px-4 py-3 text-sm text-rose-200">Some admin data could not be loaded: {errors.join(" · ")}</div> : null}

    <div className="mt-7 grid gap-6 xl:grid-cols-2"><AIWorkspaceGuestCodeForm models={activeModels} /><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-cyan-300">Model registry</p><h2 className="mt-2 text-xl font-semibold">Provider models</h2><div className="mt-4 space-y-2">{(models.data ?? []).map(row => { const config = row.config as Record<string, unknown>; const enabled = config.enabled === true; return <div key={row.id} className="rounded-xl border border-white/[.07] bg-slate-950/50 p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-200">{row.id}</p><p className="mt-1 text-[11px] text-slate-600">input {usd(config.inputRate)} / 1M · cached {usd(config.cachedInputRate)} / 1M · output {usd(config.outputRate)} / 1M · verified {when(String(config.pricingVerifiedAt ?? ""))}</p></div><form action={setModelEnabledAction}><input type="hidden" name="modelId" value={row.id}/><input type="hidden" name="enabled" value={enabled ? "false" : "true"}/><button disabled={row.id.startsWith("test-")} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${enabled ? "border-emerald-300/15 text-emerald-200" : "border-white/10 text-slate-500"} disabled:cursor-not-allowed disabled:opacity-40`}>{enabled ? "Enabled" : "Disabled"}</button></form></div></div>; })}</div></section></div>

    <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Accounts</p><h2 className="mt-2 text-xl font-semibold">Limits & credits</h2></div><p className="text-xs text-slate-600">Credit changes require a reason and append to the immutable ledger.</p></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="text-slate-600"><tr><th className="p-2">Account</th><th className="p-2">Kind</th><th className="p-2">Status</th><th className="p-2">Plan</th><th className="p-2">Daily</th><th className="p-2">Monthly</th><th className="p-2">Adjustment</th></tr></thead><tbody>{(accounts.data ?? []).map(account => <tr key={account.id} className="border-t border-white/[.06]"><td className="p-2 font-mono text-[11px] text-slate-400">{account.id.slice(0,8)}…</td><td className="p-2">{account.kind}</td><td className="p-2">{account.status}</td><td className="p-2">{account.plan_key ?? "—"}</td><td className="p-2">{usd(account.daily_limit)}</td><td className="p-2">{usd(account.monthly_limit)}</td><td className="p-2"><form action={adjustCreditAction} className="flex gap-1"><input type="hidden" name="ownerId" value={account.id}/><select name="direction" className="h-8 rounded bg-slate-900 px-2"><option value="credit">+</option><option value="debit">−</option></select><input name="amountUsd" required placeholder="USD" className="h-8 w-20 rounded bg-slate-900 px-2"/><input name="reason" required minLength={3} placeholder="Reason" className="h-8 w-36 rounded bg-slate-900 px-2"/><button className="h-8 rounded border border-white/10 px-2">Apply</button></form></td></tr>)}</tbody></table></div></section>

    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Guest codes</p><div className="mt-4 space-y-2">{(codes.data ?? []).map(code => <div key={code.id} className="rounded-xl border border-white/[.06] p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{code.label}</p><p className="mt-1 text-[11px] text-slate-600">{code.status} · {code.activation_count}/{code.max_activations} activations · {code.device_limit} devices · initial {usd(code.initial_credit)} · expires {when(code.expires_at)}</p></div>{code.status === "active" ? <form action={revokeGuestCodeAction} className="flex gap-1"><input type="hidden" name="codeId" value={code.id}/><input name="reason" required minLength={3} placeholder="Reason" className="h-8 w-28 rounded bg-slate-900 px-2 text-xs"/><button className="h-8 rounded border border-rose-300/15 px-2 text-xs text-rose-300">Revoke</button></form> : null}</div></div>)}</div></section><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Guest devices</p><div className="mt-4 space-y-2">{(devices.data ?? []).map(device => <div key={device.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/[.06] p-3"><div><p className="font-mono text-[11px] text-slate-400">{device.id.slice(0,8)}… · owner {device.owner_id.slice(0,8)}…</p><p className="mt-1 text-[11px] text-slate-600">{device.revoked ? "revoked" : "active"} · expires {when(device.expires_at)}</p></div>{!device.revoked ? <form action={revokeGuestDeviceAction} className="flex gap-1"><input type="hidden" name="deviceId" value={device.id}/><input name="reason" required minLength={3} placeholder="Reason" className="h-8 w-28 rounded bg-slate-900 px-2 text-xs"/><button className="h-8 rounded border border-rose-300/15 px-2 text-xs text-rose-300">Revoke</button></form> : null}</div>)}</div></section></div>

    <section className="mt-6 rounded-2xl border border-amber-300/10 bg-amber-400/[.025] p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-amber-300">Financial reconciliation</p><h2 className="mt-2 text-xl font-semibold">Uncertain provider spend</h2><p className="mt-2 text-xs text-slate-500">Unknown provider usage stays reserved. Release only after verifying that no charge occurred.</p><div className="mt-4 space-y-2">{(uncertain.data ?? []).length ? (uncertain.data ?? []).map(request => <div key={request.id} className="flex flex-col gap-3 rounded-xl border border-amber-300/10 bg-slate-950/40 p-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-mono text-xs text-slate-300">{request.id}</p><p className="mt-1 text-[11px] text-slate-600">owner {request.owner_id} · reserved {usd(request.reserved_micros)} · {request.request_kind} · {request.provider_state} · {request.error_code ?? "unknown error"}</p></div><form action={reconcileUncertainAction} className="flex gap-2"><input type="hidden" name="ownerId" value={request.owner_id}/><input type="hidden" name="requestId" value={request.id}/><input name="reason" required minLength={8} placeholder="Verified no provider charge because…" className="h-9 min-w-64 rounded bg-slate-900 px-3 text-xs"/><button className="h-9 rounded border border-amber-300/20 px-3 text-xs text-amber-200">Release reservation</button></form></div>) : <p className="text-sm text-slate-600">No uncertain requests.</p>}</div></section>

    <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Plans</p><h2 className="mt-2 text-xl font-semibold">Configured entitlements</h2><div className="mt-4 space-y-2">{(plans.data ?? []).length ? (plans.data ?? []).map(plan => <div key={plan.plan_key} className="rounded-xl border border-white/[.06] p-3"><p className="text-sm font-semibold">{plan.plan_key} <span className={plan.active ? "text-emerald-300" : "text-slate-600"}>{plan.active ? "active" : "inactive"}</span></p><pre className="mt-2 overflow-x-auto whitespace-pre-wrap text-[10px] text-slate-600">{JSON.stringify(plan.config,null,2)}</pre></div>) : <p className="text-sm text-slate-600">No commercial AI plan has been configured. This is intentional until product pricing and allowance are approved.</p>}</div></section><section className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Plugins</p><h2 className="mt-2 text-xl font-semibold">Connector availability</h2><div className="mt-4 space-y-2">{(plugins.data ?? []).length ? (plugins.data ?? []).map(plugin => <div key={plugin.id} className="rounded-xl border border-white/[.06] p-3"><div className="flex justify-between gap-3"><p className="text-sm font-semibold">{plugin.display_name}</p><span className="text-xs text-slate-500">{plugin.status}</span></div><p className="mt-1 text-[11px] text-slate-600">{plugin.auth_kind} · {JSON.stringify(plugin.capabilities)}</p></div>) : <p className="text-sm text-slate-600">No connector is advertised as available. Unconfigured integrations remain disabled rather than simulated.</p>}</div></section></div>

    <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-slate-500">Immutable audit</p><div className="mt-4 space-y-2">{(audit.data ?? []).map(event => <div key={event.id} className="grid gap-1 rounded-lg border border-white/[.05] px-3 py-2 text-xs sm:grid-cols-[150px_180px_1fr]"><span className="text-slate-600">{when(event.created_at)}</span><span className="font-semibold text-slate-300">{event.action}</span><span className="min-w-0 overflow-hidden text-ellipsis text-slate-600">{JSON.stringify(event.details)}</span></div>)}</div></section>
  </main>;
}

function Metric({ label, value }: { label: string; value: number }) {
  return <span className="rounded-full border border-white/10 bg-white/[.03] px-3 py-2 text-slate-400"><strong className="mr-1 text-white">{value}</strong>{label}</span>;
}
