import Link from "next/link";
import type { ApplicationRecord, JobAgent, JobAgentDashboardStats, JobOpportunity } from "@/types/jobAgent";

const statCards: Array<[keyof JobAgentDashboardStats, string]> = [
  ["jobsFound", "Jobs Found"], ["strongMatches", "Strong Matches"], ["applicationsSent", "Applications Sent"],
  ["readyForSubmit", "Ready for Submit"], ["recruiterReplies", "Recruiter Replies"], ["interviews", "Interviews"],
];

export function JobAgentDashboardView({ agent, stats, jobs, applications }: { agent: JobAgent; stats: JobAgentDashboardStats; jobs: JobOpportunity[]; applications: ApplicationRecord[] }) {
  const recommendedJobs = jobs.filter((job) => job.status !== "skipped" && job.recommendation !== "skip");
  return <>
    <section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-6" aria-label="Job Agent summary">{statCards.map(([key, label]) => <div key={key} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><p className="text-2xl font-semibold text-white">{stats[key]}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</section>
    <section className="mt-8 glass rounded-2xl border border-white/[.07] p-5 sm:p-6" aria-labelledby="matches-title"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">What jobs did you find?</p><h2 id="matches-title" className="mt-1 font-display text-xl font-semibold text-white">Latest recommendations</h2></div><p className="text-xs text-slate-500">Only language-compatible, non-skipped jobs appear here. Fit uses verified profile data.</p></div>{recommendedJobs.length ? <div className="mt-5 grid gap-4 lg:grid-cols-2">{recommendedJobs.slice(0, 12).map((job) => <article key={job.id} className="rounded-2xl border border-white/[.07] bg-black/10 p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-white">{job.role}</p><p className="mt-1 text-sm text-slate-400">{job.company}{job.location ? ` · ${job.location}` : ""}</p></div><div className="text-right"><p className="text-xl font-semibold text-cyan-200">{job.fit_score ?? "—"}%</p><p className="text-[11px] uppercase tracking-[.12em] text-slate-500">Fit</p></div></div><div className="mt-3 flex flex-wrap gap-2">{job.strengths.slice(0, 3).map((item) => <span key={item} className="rounded-full bg-emerald-400/[.08] px-2.5 py-1 text-xs text-emerald-200">{item}</span>)}</div>{job.gaps.length ? <p className="mt-3 text-xs leading-5 text-amber-200">Gap: {job.gaps.slice(0, 2).join(" · ")}</p> : null}<div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs capitalize text-slate-500">{job.status.replaceAll("_", " ")} · {job.source}</span><Link href={`/job-agent/jobs/${job.id}`} className="text-sm font-semibold text-violet-300">Review & prepare →</Link></div></article>)}</div> : <div className="mt-5 rounded-xl border border-dashed border-white/10 p-6 text-sm leading-6 text-slate-400">No eligible recommendations yet. Jobs that require a language not listed in your profile, or whose language cannot be verified when strict language filtering is enabled, are not recommended.</div>}</section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><div className="glass rounded-2xl border border-white/[.07] p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="eyebrow">Application tracker</p><h2 className="mt-1 font-display text-xl font-semibold text-white">Recent applications</h2></div><span className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-400">{agent.status}</span></div>{applications.length ? <div className="mt-5 space-y-3">{applications.slice(0, 8).map((application) => { const job = application.job_opportunities; return <article key={application.id} className="rounded-xl border border-white/[.07] bg-black/10 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold text-white">{job?.role ?? "Application"}</p><p className="mt-1 text-sm text-slate-400">{job?.company ?? "Company"}{job?.location ? ` · ${job.location}` : ""}</p></div><span className="rounded-full bg-violet-400/10 px-3 py-1 text-xs font-semibold capitalize text-violet-200">{application.status.replaceAll("_", " ")}</span></div>{application.next_action ? <p className="mt-3 text-sm text-amber-200">Action: {application.next_action}</p> : null}<Link href={`/job-agent/applications/${application.id}`} className="mt-3 inline-block text-sm font-semibold text-cyan-300">Open application pack →</Link></article>; })}</div> : <div className="mt-5 rounded-xl border border-dashed border-white/10 p-6 text-sm leading-6 text-slate-400">No applications yet. The tracker marks <strong className="text-slate-200">Applied</strong> only after real submission evidence exists.</div>}</div><div className="glass rounded-2xl border border-white/[.07] p-5 sm:p-6"><p className="eyebrow">What needs you</p><h2 className="mt-1 font-display text-xl font-semibold text-white">Required actions</h2><div className="mt-5 space-y-3">{applications.filter((item) => item.next_action || item.status === "ready_for_submit").slice(0, 6).map((item) => <Link href={`/job-agent/applications/${item.id}`} key={item.id} className="block rounded-xl border border-amber-300/15 bg-amber-400/[.04] p-4"><p className="text-sm font-semibold text-amber-100">{item.status === "ready_for_submit" ? "Ready for Submit" : "Decision required"}</p><p className="mt-1 text-sm leading-6 text-slate-400">{item.next_action ?? "Open the saved ATS application and press Submit after review."}</p></Link>)}{!applications.some((item) => item.next_action || item.status === "ready_for_submit") ? <p className="rounded-xl border border-white/[.07] p-4 text-sm leading-6 text-slate-400">Nothing requires your attention right now.</p> : null}</div></div></section>
  </>;
}
