const SKILL_PATTERNS: Array<[string, RegExp]> = [
  ["Power BI", /\bpower\s*bi\b/i],
  ["Power Automate", /\bpower\s*automate\b/i],
  ["Power Apps", /\bpower\s*apps\b/i],
  ["Power Platform", /\bpower\s*platform\b/i],
  ["Copilot Studio", /\bcopilot\s*studio\b/i],
  ["Dataverse", /\bdataverse\b/i],
  ["Microsoft Fabric", /\b(?:microsoft\s+)?fabric\b/i],
  ["DAX", /\bdax\b/i],
  ["Power Query", /\bpower\s*query\b/i],
  ["Excel", /\bexcel\b/i],
  ["SQL", /\bsql\b/i],
  ["Python", /\bpython\b/i],
  ["Pandas", /\bpandas\b/i],
  ["Tableau", /\btableau\b/i],
  ["Data Analysis", /\bdata\s+analys(?:is|tics)\b/i],
  ["Data Modeling", /\bdata\s+modell?ing\b/i],
  ["ETL", /\betl\b/i],
  ["Forecasting", /\bforecast(?:ing)?\b/i],
  ["AI Automation", /\bai\s+automation\b/i],
  ["Workflow Automation", /\bworkflow\s+automation\b/i],
  ["Process Automation", /\bprocess\s+automation\b/i],
  ["RPA", /\brpa\b/i],
  ["n8n", /\bn8n\b/i],
  ["Zapier", /\bzapier\b/i],
  ["Make.com", /\bmake\.com\b/i],
  ["REST API", /\brest\s+api(?:s)?\b/i],
  ["API Integration", /\bapi\s+integration\b/i],
  ["Webhooks", /\bwebhooks?\b/i],
  ["Generative AI", /\bgenerative\s+ai\b/i],
  ["LLM", /\bllms?\b/i],
  ["OpenAI", /\bopenai\b/i],
  ["Prompt Engineering", /\bprompt\s+engineering\b/i],
  ["RAG", /\b(?:rag|retrieval\s+augmented\s+generation)\b/i],
  ["AI Agents", /\bai\s+agents?\b/i],
  ["Machine Learning", /\bmachine\s+learning\b/i],
  ["Business Analysis", /\bbusiness\s+analys(?:is|t)\b/i],
  ["Requirements Gathering", /\brequirements?\s+(?:gathering|analysis)\b/i],
  ["Stakeholder Management", /\bstakeholder\s+management\b/i],
  ["Process Mapping", /\bprocess\s+mapping\b/i],
  ["Digital Transformation", /\bdigital\s+transformation\b/i],
  ["Solution Design", /\bsolution\s+design\b/i],
  ["JavaScript", /\bjavascript\b/i],
  ["TypeScript", /\btypescript\b/i],
  ["React", /\breact(?:\.js)?\b/i],
  ["Next.js", /\bnext\.?js\b/i],
  ["Node.js", /\bnode\.?js\b/i],
  ["Git", /\bgit\b/i],
  ["GitHub", /\bgithub\b/i],
  ["Docker", /\bdocker\b/i],
  ["Azure", /\bazure\b/i],
  ["AWS", /\baws\b/i],
  ["GCP", /\bgcp\b/i],
  ["Supabase", /\bsupabase\b/i],
  ["Vercel", /\bvercel\b/i],
  ["SEO", /\bseo\b/i],
  ["Google Analytics", /\bgoogle\s+analytics\b/i],
];

export function extractMasterCvSkills(text: string): string[] {
  const normalized = text.replace(/\u0000/g, " ");
  return SKILL_PATTERNS.filter(([, pattern]) => pattern.test(normalized)).map(([skill]) => skill);
}
