"use client";
import { useMemo, useState } from "react";
import type { CareerWorkspaceData } from "@/types/careerWorkspace";

type AIDraft={category:string;shortDescription:string;difficulty:string;estimatedLearningTime:string;overview:{title:string;body:string;responsibilities:string[];industries:string[]};journeyMap:{overviewTitle:string;overviewDescription:string};stages:Array<{id:string;title:string;description:string;learningGoals:string[]}>;roadmap:Array<{title:string;description:string;outcomes:string[]}>;projects:Array<{title:string;description:string;skills:string[]}>;resourceNeeds:Array<{stageId:string;topic:string;preferredProviderTypes:string[];searchIntent:string}>;qualityNotes:string[]};
type Workspace=Record<string,any>;

const inputClass="input-field mt-1 min-h-11 w-full";
const textareaClass="input-field mt-1 w-full resize-y";

export default function CareerContentEditor({careerId,slug,data,action}:{careerId:string;slug:string;data:CareerWorkspaceData|null;action:(formData:FormData)=>void}){
  const [workspace,setWorkspace]=useState<Workspace>(()=>structuredClone((data??starter(slug)) as Workspace));
  const [mode,setMode]=useState<"visual"|"json">("visual");
  const [jsonValue,setJsonValue]=useState(()=>JSON.stringify(workspace,null,2));
  const [aiState,setAiState]=useState<{status:"idle"|"working"|"ready"|"error";message?:string;draft?:AIDraft}>({status:"idle"});
  const serialized=useMemo(()=>JSON.stringify(workspace,null,2),[workspace]);
  const summary=`${workspace.journeyStages?.length??0} stages · ${workspace.roadmap?.length??0} phases · ${workspace.projects?.length??0} projects`;

  function commit(next:Workspace){setWorkspace(next);setJsonValue(JSON.stringify(next,null,2))}
  function patch(path:string[],value:any){const next=structuredClone(workspace);let node=next;for(const key of path.slice(0,-1)){node[key]??={};node=node[key]}node[path.at(-1)!]=value;commit(next)}
  function patchList(path:string[],index:number,key:string,value:any){const next=structuredClone(workspace);let node=next;for(const segment of path)node=node[segment];node[index]={...node[index],[key]:value};commit(next)}
  function removeList(path:string[],index:number){const next=structuredClone(workspace);let node=next;for(const segment of path)node=node[segment];node.splice(index,1);commit(next)}
  function addList(path:string[],item:any){const next=structuredClone(workspace);let node=next;for(const segment of path.slice(0,-1)){node[segment]??={};node=node[segment]}const key=path.at(-1)!;node[key]=[...(node[key]??[]),item];commit(next)}
  function moveList(path:string[],index:number,direction:-1|1){const next=structuredClone(workspace);let node=next;for(const segment of path)node=node[segment];const target=index+direction;if(target<0||target>=node.length)return;[node[index],node[target]]=[node[target],node[index]];commit(next)}
  function applyJson(){try{const parsed=JSON.parse(jsonValue);commit(parsed);setMode("visual")}catch{setAiState({status:"error",message:"Advanced JSON is invalid. Fix the JSON before applying it."})}}

  async function generateWithAI(){if(aiState.status==="working")return;setAiState({status:"working",message:"Generating a role-specific Career blueprint…"});try{const response=await fetch("/api/admin/ai/career-draft",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({careerId})});const body=await response.json() as {draft?:AIDraft;message?:string;error?:string};if(!response.ok||!body.draft)throw new Error(body.message||body.error||"AI generation failed.");setAiState({status:"ready",message:"AI draft generated. Review it, then apply it to the working draft.",draft:body.draft})}catch(error){setAiState({status:"error",message:error instanceof Error?error.message:"AI generation failed."})}}
  function applyAIDraft(){const draft=aiState.draft;if(!draft)return;const current=structuredClone(workspace);const next={...current,category:draft.category,shortDescription:draft.shortDescription,difficulty:draft.difficulty,estimatedLearningTime:draft.estimatedLearningTime,overview:draft.overview,journeyMap:{...(current.journeyMap??{}),overviewTitle:draft.journeyMap.overviewTitle,overviewDescription:draft.journeyMap.overviewDescription},journeyStages:draft.stages.map((stage,index)=>({id:stage.id,order:index+1,title:stage.title,type:index===0?"orientation":index===draft.stages.length-1?"assessment":"core-skills",landmark:`Stage ${index+1}`,theme:"Career progression",x:18+index*12,y:24+((index%2)*16),summary:stage.description,explanation:stage.description,lessons:stage.learningGoals,resources:[],tasks:[],topicAssessments:[],phaseExam:null})),roadmap:draft.roadmap.map((phase,index)=>({id:`phase-${index+1}`,phaseNumber:index+1,title:phase.title,duration:"To be estimated",goal:phase.description,status:index===0?"unlocked":"locked",mentorTip:"Review and customize this AI-generated draft before publication.",sections:phase.outcomes,lessons:[],practicalMissions:phase.outcomes,expectedOutcome:phase.outcomes.join(" "),quiz:{id:`phase-${index+1}-quiz`,title:`${phase.title} review`,description:"Assessment content must be generated and reviewed separately.",questions:[]}})),projects:draft.projects.map((project,index)=>({id:`project-${index+1}`,title:project.title,difficulty:index===0?"Beginner":index===draft.projects.length-1?"Advanced":"Intermediate",estimatedTime:"To be estimated",phaseId:`phase-${Math.min(index+1,draft.roadmap.length)}`,description:project.description,deliverables:[],skills:project.skills})),lastUpdated:new Date().toISOString().slice(0,10)};commit(next);setAiState(s=>({...s,message:`AI blueprint applied. ${draft.resourceNeeds.length} resource needs remain for the verified Resource Finder workflow.`}))}

  return <form action={action} className="space-y-5"><input type="hidden" name="id" value={careerId}/><input type="hidden" name="workspaceData" value={serialized}/>
    <section className="rounded-xl border border-cyan-300/15 bg-cyan-400/5 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-white">AI Content Copilot</p><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-400">Generate a role-specific first draft. AI cannot publish. Resource URLs, salary evidence, assessments and externally verifiable claims remain behind separate review workflows.</p></div><div className="flex gap-2"><button type="button" onClick={()=>void generateWithAI()} disabled={aiState.status==="working"} className="btn-secondary min-h-11 disabled:opacity-50">{aiState.status==="working"?"Generating…":"Generate with AI"}</button>{aiState.draft?<button type="button" onClick={applyAIDraft} className="btn-primary min-h-11">Apply draft</button>:null}</div></div>{aiState.message?<p aria-live="polite" className={`mt-3 text-xs ${aiState.status==="error"?"text-rose-300":"text-slate-300"}`}>{aiState.message}</p>:null}</section>

    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[.025] p-4"><div><p className="font-semibold text-white">Career Content Studio</p><p className="mt-1 text-xs text-emerald-300">{summary}</p></div><div className="flex gap-2"><button type="button" onClick={()=>setMode("visual")} className={mode==="visual"?"btn-primary min-h-11":"btn-secondary min-h-11"}>Visual editor</button><button type="button" onClick={()=>{setJsonValue(serialized);setMode("json")}} className={mode==="json"?"btn-primary min-h-11":"btn-secondary min-h-11"}>Advanced JSON</button><button className="btn-primary min-h-11">Validate & save</button></div></div>

    {mode==="visual"?<div className="space-y-5">
      <Section title="Career foundation" description="Core user-facing Career information."><div className="grid gap-4 md:grid-cols-2"><Field label="Career title"><input className={inputClass} value={workspace.title??""} onChange={e=>patch(["title"],e.target.value)}/></Field><Field label="Category"><input className={inputClass} value={workspace.category??""} onChange={e=>patch(["category"],e.target.value)}/></Field><Field label="Difficulty"><input className={inputClass} value={workspace.difficulty??""} onChange={e=>patch(["difficulty"],e.target.value)}/></Field><Field label="Estimated learning time"><input className={inputClass} value={workspace.estimatedLearningTime??""} onChange={e=>patch(["estimatedLearningTime"],e.target.value)}/></Field></div><Field label="Short description"><textarea rows={4} className={textareaClass} value={workspace.shortDescription??""} onChange={e=>patch(["shortDescription"],e.target.value)}/></Field></Section>

      <Section title="Overview" description="Role-specific overview, responsibilities and industries."><Field label="Overview title"><input className={inputClass} value={workspace.overview?.title??""} onChange={e=>patch(["overview","title"],e.target.value)}/></Field><Field label="Overview body"><textarea rows={7} className={textareaClass} value={workspace.overview?.body??""} onChange={e=>patch(["overview","body"],e.target.value)}/></Field><StringList title="Responsibilities" values={workspace.overview?.responsibilities??[]} onChange={v=>patch(["overview","responsibilities"],v)}/><StringList title="Industries" values={workspace.overview?.industries??[]} onChange={v=>patch(["overview","industries"],v)}/></Section>

      <Section title="Roadmap" description="Add, edit, remove and reorder Career roadmap phases."><div className="space-y-3">{(workspace.roadmap??[]).map((phase:any,index:number)=><article key={phase.id??index} className="rounded-xl border border-white/10 bg-white/[.02] p-4"><CollectionToolbar index={index} length={workspace.roadmap.length} onMove={d=>moveList(["roadmap"],index,d)} onDelete={()=>removeList(["roadmap"],index)}/><div className="grid gap-3 md:grid-cols-2"><Field label="Phase title"><input className={inputClass} value={phase.title??""} onChange={e=>patchList(["roadmap"],index,"title",e.target.value)}/></Field><Field label="Duration"><input className={inputClass} value={phase.duration??""} onChange={e=>patchList(["roadmap"],index,"duration",e.target.value)}/></Field></div><Field label="Goal"><textarea rows={3} className={textareaClass} value={phase.goal??""} onChange={e=>patchList(["roadmap"],index,"goal",e.target.value)}/></Field><StringList title="Sections / outcomes" values={phase.sections??[]} onChange={v=>patchList(["roadmap"],index,"sections",v)}/></article>)}</div><button type="button" onClick={()=>addList(["roadmap"],blankRoadmap((workspace.roadmap?.length??0)+1))} className="btn-secondary mt-4 min-h-11">+ Add roadmap phase</button></Section>

      <Section title="Projects" description="Portfolio-building projects attached to the Career."><div className="space-y-3">{(workspace.projects??[]).map((project:any,index:number)=><article key={project.id??index} className="rounded-xl border border-white/10 bg-white/[.02] p-4"><CollectionToolbar index={index} length={workspace.projects.length} onMove={d=>moveList(["projects"],index,d)} onDelete={()=>removeList(["projects"],index)}/><div className="grid gap-3 md:grid-cols-2"><Field label="Project title"><input className={inputClass} value={project.title??""} onChange={e=>patchList(["projects"],index,"title",e.target.value)}/></Field><Field label="Difficulty"><select className={inputClass} value={project.difficulty??"Intermediate"} onChange={e=>patchList(["projects"],index,"difficulty",e.target.value)}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></Field><Field label="Estimated time"><input className={inputClass} value={project.estimatedTime??""} onChange={e=>patchList(["projects"],index,"estimatedTime",e.target.value)}/></Field><Field label="Phase ID"><input className={inputClass} value={project.phaseId??""} onChange={e=>patchList(["projects"],index,"phaseId",e.target.value)}/></Field></div><Field label="Description"><textarea rows={4} className={textareaClass} value={project.description??""} onChange={e=>patchList(["projects"],index,"description",e.target.value)}/></Field><StringList title="Skills" values={project.skills??[]} onChange={v=>patchList(["projects"],index,"skills",v)}/><StringList title="Deliverables" values={project.deliverables??[]} onChange={v=>patchList(["projects"],index,"deliverables",v)}/></article>)}</div><button type="button" onClick={()=>addList(["projects"],blankProject((workspace.projects?.length??0)+1))} className="btn-secondary mt-4 min-h-11">+ Add project</button></Section>

      <section className="rounded-2xl border border-dashed border-white/15 p-5"><h3 className="font-semibold text-white">Next structured sections</h3><p className="mt-2 text-sm text-slate-400">Learning resources, assessments, final challenge, portfolio, job search and interview preparation remain editable through Advanced JSON for this iteration. They are the next CMS modules to convert.</p></section>
    </div>:<section className="space-y-3"><p className="text-sm text-amber-100">Advanced mode exposes the complete workspace contract. Use it only for fields not yet available in the visual editor.</p><textarea aria-label="Career workspace JSON" spellCheck={false} value={jsonValue} onChange={e=>setJsonValue(e.target.value)} className="min-h-[65vh] w-full rounded-2xl border border-white/10 bg-[#060914] p-5 font-mono text-xs leading-6 text-slate-200 outline-none focus:border-cyan-300/50"/><div className="flex justify-end"><button type="button" onClick={applyJson} className="btn-secondary min-h-11">Apply JSON changes</button></div></section>}
  </form>
}

function Section({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div><h3 className="font-semibold text-white">{title}</h3><p className="mt-1 text-xs text-slate-500">{description}</p></div>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm text-slate-300">{label}{children}</label>}
function StringList({title,values,onChange}:{title:string;values:string[];onChange:(values:string[])=>void}){return <div><div className="flex items-center justify-between"><p className="text-sm text-slate-300">{title}</p><button type="button" onClick={()=>onChange([...values,""])} className="text-xs font-semibold text-cyan-300">+ Add</button></div><div className="mt-2 space-y-2">{values.map((value,index)=><div key={index} className="flex gap-2"><input className={inputClass} value={value} onChange={e=>onChange(values.map((item,i)=>i===index?e.target.value:item))}/><button type="button" aria-label={`Remove ${title} item ${index+1}`} onClick={()=>onChange(values.filter((_,i)=>i!==index))} className="min-h-11 rounded-xl border border-white/10 px-3 text-slate-400">×</button></div>)}</div></div>}
function CollectionToolbar({index,length,onMove,onDelete}:{index:number;length:number;onMove:(d:-1|1)=>void;onDelete:()=>void}){return <div className="mb-3 flex justify-end gap-2"><button type="button" disabled={index===0} onClick={()=>onMove(-1)} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-30">↑</button><button type="button" disabled={index===length-1} onClick={()=>onMove(1)} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-30">↓</button><button type="button" onClick={onDelete} className="rounded-lg border border-rose-300/20 px-3 py-2 text-xs text-rose-200">Remove</button></div>}
function blankRoadmap(n:number){return{id:`phase-${n}`,phaseNumber:n,title:"New phase",duration:"",goal:"",status:n===1?"unlocked":"locked",mentorTip:"",sections:[],lessons:[],practicalMissions:[],expectedOutcome:"",quiz:{id:`phase-${n}-quiz`,title:"Phase review",description:"",questions:[]}}}
function blankProject(n:number){return{id:`project-${n}`,title:"New project",difficulty:"Intermediate",estimatedTime:"",phaseId:"phase-1",description:"",deliverables:[],skills:[]}}
function starter(slug:string):Partial<CareerWorkspaceData>{return{slug,title:"New Career",category:"AI",visual:{nodeLabel:`Career Node: ${slug}`,sceneTitle:"Career workspace",sceneDescription:"A guided professional journey.",imageAlt:"Career journey workspace"},shortDescription:"Complete this description before publishing.",difficulty:"Beginner to Intermediate",estimatedLearningTime:"6-12 months",salary:"Research required",hiringDemand:"Research required",remoteAvailability:"Research required",aiCompatibilityScore:"Research required",bestFor:[],programmingRequirement:"Define requirement",mathRequirement:"Define requirement",creativityLevel:"Define level",communicationLevel:"Define level",lastUpdated:new Date().toISOString().slice(0,10),metrics:[],overview:{title:"Career overview",body:"Complete this overview.",responsibilities:[],industries:[]},mapSections:[],journeyMap:{theme:"treasure-map",overviewTitle:"Career journey",overviewDescription:"Complete journey overview."},journeyStages:[],roadmap:[],projects:[],globalResources:[],readiness:[],finalChallenge:{title:"Final challenge",description:"Complete this challenge.",requirements:[],deliverables:[],evaluation:[]},relatedCareers:[],progressRules:{readinessThreshold:80,minimumProjects:2,minimumQuizScore:80},jobBoard:{title:"Career opportunities",description:"Curated opportunities.",integrationStatus:"coming-soon",filters:[],sampleDisclaimer:"Job data is illustrative until live integration is enabled."},portfolioTasks:[],jobSearchTasks:[],interviewPrep:{title:"Interview preparation",practiceAreas:[],questions:[]}}}
