"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import type { CareerStudioSection, CompletenessState, PublicationReadiness } from "@/lib/admin/careerStudio";

export interface CareerMatrixItem {
  slug:string; title:string; domain:string; availability:"available"|"planned"; careerId:string|null;
  contentStatus:"published"|"draft"|"empty"|"coming-soon"|"archived"; completion:number;
  readiness:PublicationReadiness; missingCount:number; updatedAt:string|null; publishedAt:string|null;
  sections:{id:CareerStudioSection;label:string;score:number;state:CompletenessState}[];
}
type Filter="all"|"ready"|"incomplete"|"empty"|"published"|"draft"|"coming-soon";
type Sort="completion"|"name"|"updated"|"readiness"|"missing";
const filters:{id:Filter;label:string}[]=[{id:"all",label:"All"},{id:"ready",label:"Ready to publish"},{id:"incomplete",label:"Incomplete"},{id:"empty",label:"Empty"},{id:"published",label:"Published"},{id:"draft",label:"Draft"},{id:"coming-soon",label:"Coming Soon"}];
const stateLabel:Record<CompletenessState,string>={complete:"✓ Complete",partial:"◐ Partial",missing:"— Missing","not-applicable":"○ N/A",error:"! Error"};
const stateStyle:Record<CompletenessState,string>={complete:"text-emerald-200",partial:"text-amber-200",missing:"text-rose-200","not-applicable":"text-slate-500",error:"text-rose-200"};

export default function CareerCompletenessMatrix({items}:{items:CareerMatrixItem[]}){
  const [query,setQuery]=useState(""),[filter,setFilter]=useState<Filter>("all"),[sort,setSort]=useState<Sort>("completion");
  const visible=useMemo(()=>items.filter((item)=>item.title.toLowerCase().includes(query.trim().toLowerCase())).filter((item)=>filter==="all"||filter==="ready"&&["ready","ready-with-warnings"].includes(item.readiness)||filter==="incomplete"&&item.readiness==="not-ready"||filter==="empty"&&item.contentStatus==="empty"||filter==="published"&&item.contentStatus==="published"||filter==="draft"&&item.contentStatus==="draft"||filter==="coming-soon"&&item.contentStatus==="coming-soon").sort((a,b)=>sort==="name"?a.title.localeCompare(b.title):sort==="updated"?(Date.parse(b.updatedAt??"")||0)-(Date.parse(a.updatedAt??"")||0):sort==="readiness"?readinessRank(a.readiness)-readinessRank(b.readiness):sort==="missing"?b.missingCount-a.missingCount:b.completion-a.completion),[items,query,filter,sort]);
  return <>
    <div className="mt-6 rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="grid gap-3 lg:grid-cols-[minmax(220px,1fr)_220px]"><label className="text-xs font-medium text-slate-400">Search Careers<input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Career name" className="input-field mt-2 min-h-11 w-full"/></label><label className="text-xs font-medium text-slate-400">Sort by<select value={sort} onChange={(event)=>setSort(event.target.value as Sort)} className="input-field mt-2 min-h-11 w-full"><option value="completion">Completion score</option><option value="name">Career name</option><option value="updated">Last updated</option><option value="readiness">Publication readiness</option><option value="missing">Missing sections</option></select></label></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1" aria-label="Filter Careers">{filters.map((item)=><button key={item.id} type="button" aria-pressed={filter===item.id} onClick={()=>setFilter(item.id)} className={`min-h-10 shrink-0 rounded-lg border px-3 text-xs font-semibold ${filter===item.id?"border-indigo-400/40 bg-indigo-400/15 text-indigo-100":"border-white/10 text-slate-400 hover:text-white"}`}>{item.label}</button>)}</div></div>
    <p className="mt-4 text-xs text-slate-500" aria-live="polite">Showing {visible.length} of {items.length} supported Careers.</p>
    <div className="mt-3 overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-[1680px] w-full border-collapse text-left"><caption className="sr-only">Content completeness for every supported Career</caption><thead className="bg-slate-950"><tr>{["Career","Overview","Roadmap","Learning","Interview","Jobs","Salary","Skills","Projects","SEO","Settings","Overall","Publication","Readiness"].map((heading,index)=><th key={heading} scope="col" className={`border-b border-white/10 px-3 py-3 text-[10px] font-semibold uppercase tracking-wide text-slate-500 ${index===0?"sticky left-0 z-20 min-w-56 bg-slate-950":"min-w-28"}`}>{heading}</th>)}</tr></thead><tbody>{visible.map((item)=><tr key={item.slug} className="border-b border-white/[.07] last:border-b-0 hover:bg-white/[.02]"><th scope="row" className="sticky left-0 z-10 bg-[#070a16] px-3 py-4"><Link href={item.careerId?`/admin/careers/${item.careerId}`:`/admin/careers/new?slug=${item.slug}&title=${encodeURIComponent(item.title)}`} className="font-semibold text-white hover:text-cyan-200">{item.title}</Link><span className="mt-1 block text-[10px] font-normal text-slate-500">{item.availability==="planned"?"Coming Soon":item.domain}</span></th>{item.sections.map((section)=><td key={section.id} className="px-3 py-3"><Link aria-label={`${item.title} ${section.label}: ${stateLabel[section.state]}, ${section.score}%`} href={item.careerId?`/admin/careers/${item.careerId}/content?section=${section.id}`:`/admin/careers/new?slug=${item.slug}&title=${encodeURIComponent(item.title)}`} className={`block rounded-lg border border-white/[.07] px-2 py-2 text-[10px] font-semibold hover:bg-white/5 ${stateStyle[section.state]}`}><span className="block whitespace-nowrap">{stateLabel[section.state]}</span><span className="mt-1 block text-slate-500">{section.score}%</span></Link></td>)}<td className="px-3 py-3"><span className="font-semibold text-white">{item.completion}%</span><span className="mt-1 block text-[10px] text-slate-500">{item.missingCount} missing</span></td><td className="px-3 py-3"><Status value={item.contentStatus}/></td><td className="px-3 py-3"><Readiness value={item.readiness}/></td></tr>)}</tbody></table></div>
  </>;
}
function readinessRank(value:PublicationReadiness){return({ready:0,"ready-with-warnings":1,published:2,"not-ready":3,"coming-soon":4})[value]}
function Status({value}:{value:CareerMatrixItem["contentStatus"]}){return <span className="inline-flex rounded-full border border-white/10 px-2 py-1 text-[10px] font-semibold uppercase text-slate-300">{value.replace("-"," ")}</span>}
function Readiness({value}:{value:PublicationReadiness}){const label={ready:"✓ Ready","ready-with-warnings":"! Ready with warnings","not-ready":"× Not ready",published:"✓ Published","coming-soon":"○ Coming Soon"}[value];return <span className="text-xs font-semibold text-slate-300">{label}</span>}
