"use client";
import { useMemo, useState } from "react";
import type { CareerWorkspaceData } from "@/types/careerWorkspace";

export default function CareerContentEditor({careerId,slug,data,action}:{careerId:string;slug:string;data:CareerWorkspaceData|null;action:(formData:FormData)=>void}){
  const [value,setValue]=useState(()=>JSON.stringify(data??starter(slug),null,2));
  const state=useMemo(()=>{try{const parsed=JSON.parse(value);return{ok:true,summary:`${parsed.journeyStages?.length??0} stages · ${parsed.roadmap?.length??0} phases · ${parsed.projects?.length??0} projects`}}catch(error){return{ok:false,summary:error instanceof Error?error.message:"Invalid JSON"}}},[value]);
  return <form action={action} className="space-y-4"><input type="hidden" name="id" value={careerId}/><div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[.025] p-4"><div><p className="font-semibold text-white">Workspace content</p><p className={`mt-1 text-xs ${state.ok?"text-emerald-300":"text-rose-300"}`}>{state.ok?state.summary:`JSON error: ${state.summary}`}</p></div><button disabled={!state.ok} className="btn-primary min-h-11 disabled:cursor-not-allowed disabled:opacity-40">Validate & save</button></div><textarea aria-label="Career workspace JSON" spellCheck={false} name="workspaceData" value={value} onChange={event=>setValue(event.target.value)} className="min-h-[65vh] w-full rounded-2xl border border-white/10 bg-[#060914] p-5 font-mono text-xs leading-6 text-slate-200 outline-none focus:border-cyan-300/50"/></form>
}

function starter(slug:string):Partial<CareerWorkspaceData>{return{slug,title:"New Career",category:"AI",visual:{nodeLabel:`Career Node: ${slug}`,sceneTitle:"Career workspace",sceneDescription:"A guided professional journey.",imageAlt:"Career journey workspace"},shortDescription:"Complete this description before publishing.",difficulty:"Beginner to Intermediate",estimatedLearningTime:"6-12 months",salary:"Research required",hiringDemand:"Research required",remoteAvailability:"Research required",aiCompatibilityScore:"Research required",bestFor:[],programmingRequirement:"Define requirement",mathRequirement:"Define requirement",creativityLevel:"Define level",communicationLevel:"Define level",lastUpdated:new Date().toISOString().slice(0,10),metrics:[],overview:{title:"Career overview",body:"Complete this overview.",responsibilities:[],industries:[]},mapSections:[],journeyMap:{theme:"treasure-map",overviewTitle:"Career journey",overviewDescription:"Complete journey overview."},journeyStages:[],roadmap:[],projects:[],globalResources:[],readiness:[],finalChallenge:{title:"Final challenge",description:"Complete this challenge.",requirements:[],deliverables:[],evaluation:[]},relatedCareers:[],progressRules:{readinessThreshold:80,minimumProjects:2,minimumQuizScore:80},jobBoard:{title:"Career opportunities",description:"Curated opportunities.",integrationStatus:"coming-soon",filters:[],sampleDisclaimer:"Job data is illustrative until live integration is enabled."},portfolioTasks:[],jobSearchTasks:[],interviewPrep:{title:"Interview preparation",practiceAreas:[],questions:[]}}}
