"use client";
import { useMemo,useState } from "react";
import type { CareerWorkspaceData } from "@/types/careerWorkspace";

const inputClass="input-field mt-1 min-h-11 w-full";
const textareaClass="input-field mt-1 w-full resize-y";
type Candidate={title:string;provider:string;url:string;resourceType:string;cost:string;estimatedTime:string;whyUseful:string;authorityTier:string;directYouTube:boolean;verificationNotes:string[]};

type Props={careerId:string;data:CareerWorkspaceData;action:(formData:FormData)=>void};
export default function LearningContentEditor({careerId,data,action}:Props){
  const [workspace,setWorkspace]=useState<any>(()=>structuredClone(data));
  const [finder,setFinder]=useState<{stageIndex:number|null;topic:string;status:"idle"|"working"|"ready"|"error";message?:string;candidates:Candidate[]}>({stageIndex:null,topic:"",status:"idle",candidates:[]});
  const serialized=useMemo(()=>JSON.stringify(workspace,null,2),[workspace]);
  const stages:any[]=workspace.journeyStages??[];

  function commit(next:any){setWorkspace(next)}
  function patchStage(index:number,key:string,value:any){const next=structuredClone(workspace);next.journeyStages[index]={...next.journeyStages[index],[key]:value};commit(next)}
  function addStage(){const next=structuredClone(workspace);const n=(next.journeyStages?.length??0)+1;next.journeyStages=[...(next.journeyStages??[]),{id:`stage-${n}`,order:n,title:`Learning stage ${n}`,type:"core-skills",landmark:`Stage ${n}`,theme:"Career progression",x:20+n*8,y:28+(n%2)*14,summary:"",explanation:"",lessons:[],resources:[],tasks:[],topicAssessments:[],phaseExam:null}];commit(next)}
  function removeStage(index:number){const next=structuredClone(workspace);next.journeyStages.splice(index,1);next.journeyStages.forEach((s:any,i:number)=>s.order=i+1);commit(next)}
  function moveStage(index:number,direction:-1|1){const next=structuredClone(workspace);const target=index+direction;if(target<0||target>=next.journeyStages.length)return;[next.journeyStages[index],next.journeyStages[target]]=[next.journeyStages[target],next.journeyStages[index]];next.journeyStages.forEach((s:any,i:number)=>s.order=i+1);commit(next)}
  function patchResource(stageIndex:number,resourceIndex:number,key:string,value:any){const next=structuredClone(workspace);next.journeyStages[stageIndex].resources[resourceIndex]={...next.journeyStages[stageIndex].resources[resourceIndex],[key]:value};commit(next)}
  function addResource(stageIndex:number,resource?:Partial<any>){const next=structuredClone(workspace);const resources=next.journeyStages[stageIndex].resources??[];const n=resources.length+1;next.journeyStages[stageIndex].resources=[...resources,{id:`${next.journeyStages[stageIndex].id}-resource-${n}`,title:resource?.title??"New resource",type:resource?.type??"Course",provider:resource?.provider??"",cost:resource?.cost??"Free",estimatedTime:resource?.estimatedTime??"",whyUseful:resource?.whyUseful??"",url:resource?.url??"",priority:resource?.priority??"Recommended"}];commit(next)}
  function removeResource(stageIndex:number,resourceIndex:number){const next=structuredClone(workspace);next.journeyStages[stageIndex].resources.splice(resourceIndex,1);commit(next)}
  function moveResource(stageIndex:number,resourceIndex:number,direction:-1|1){const next=structuredClone(workspace);const items=next.journeyStages[stageIndex].resources;const target=resourceIndex+direction;if(target<0||target>=items.length)return;[items[resourceIndex],items[target]]=[items[target],items[resourceIndex]];commit(next)}

  async function discover(stageIndex:number){const topic=finder.stageIndex===stageIndex?finder.topic.trim():"";if(topic.length<3){setFinder(s=>({...s,stageIndex,status:"error",message:"Enter a learning topic first."}));return}setFinder(s=>({...s,stageIndex,status:"working",message:"Searching and ranking authoritative learning resources…",candidates:[]}));try{const response=await fetch("/api/admin/ai/resource-discovery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({careerId,stageTitle:stages[stageIndex].title,topic})});const body=await response.json();if(!response.ok)throw new Error(body.message||body.error||"Resource discovery failed.");setFinder(s=>({...s,stageIndex,status:"ready",message:"Review candidates before adding them to Learning.",candidates:body.candidates??[]}))}catch(error){setFinder(s=>({...s,stageIndex,status:"error",message:error instanceof Error?error.message:"Resource discovery failed.",candidates:[]}))}}
  function approveCandidate(stageIndex:number,candidate:Candidate){addResource(stageIndex,{title:candidate.title,type:normalizeType(candidate.resourceType),provider:candidate.provider,cost:normalizeCost(candidate.cost),estimatedTime:candidate.estimatedTime,whyUseful:candidate.whyUseful,url:candidate.url,priority:"Recommended"});setFinder(s=>({...s,message:`Added ${candidate.title} to the working draft. Save and validate when ready.`}))}

  return <form action={action} className="space-y-5"><input type="hidden" name="id" value={careerId}/><input type="hidden" name="workspaceData" value={serialized}/>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[.025] p-4"><div><h2 className="font-semibold text-white">Learning CMS</h2><p className="mt-1 text-xs text-slate-400">{stages.length} stages · {stages.reduce((sum:number,s:any)=>sum+(s.resources?.length??0),0)} learning resources</p></div><div className="flex gap-2"><button type="button" onClick={addStage} className="btn-secondary min-h-11">+ Add stage</button><button className="btn-primary min-h-11">Validate & save</button></div></div>
    {stages.map((stage:any,stageIndex:number)=><section key={stage.id??stageIndex} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wide text-slate-500">Stage {stageIndex+1}</p><h3 className="mt-1 font-semibold text-white">{stage.title||"Untitled stage"}</h3></div><div className="flex gap-2"><button type="button" disabled={stageIndex===0} onClick={()=>moveStage(stageIndex,-1)} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-30">↑</button><button type="button" disabled={stageIndex===stages.length-1} onClick={()=>moveStage(stageIndex,1)} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-30">↓</button><button type="button" onClick={()=>removeStage(stageIndex)} className="rounded-lg border border-rose-300/20 px-3 py-2 text-xs text-rose-200">Delete stage</button></div></div>
      <div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Stage ID"><input className={inputClass} value={stage.id??""} onChange={e=>patchStage(stageIndex,"id",e.target.value)}/></Field><Field label="Title"><input className={inputClass} value={stage.title??""} onChange={e=>patchStage(stageIndex,"title",e.target.value)}/></Field><Field label="Type"><input className={inputClass} value={stage.type??""} onChange={e=>patchStage(stageIndex,"type",e.target.value)}/></Field><Field label="Landmark"><input className={inputClass} value={stage.landmark??""} onChange={e=>patchStage(stageIndex,"landmark",e.target.value)}/></Field></div><Field label="Summary"><textarea rows={3} className={textareaClass} value={stage.summary??""} onChange={e=>patchStage(stageIndex,"summary",e.target.value)}/></Field><Field label="Explanation"><textarea rows={4} className={textareaClass} value={stage.explanation??""} onChange={e=>patchStage(stageIndex,"explanation",e.target.value)}/></Field>
      <div className="mt-5 rounded-xl border border-cyan-300/15 bg-cyan-400/5 p-4"><div className="flex flex-wrap gap-3"><input value={finder.stageIndex===stageIndex?finder.topic:""} onChange={e=>setFinder(s=>({...s,stageIndex,topic:e.target.value,status:"idle",candidates:[]}))} placeholder="Topic, e.g. Power Automate cloud flows" className="input-field min-h-11 flex-1"/><button type="button" disabled={finder.status==="working"&&finder.stageIndex===stageIndex} onClick={()=>void discover(stageIndex)} className="btn-secondary min-h-11">{finder.status==="working"&&finder.stageIndex===stageIndex?"Searching…":"AI Resource Finder"}</button></div>{finder.stageIndex===stageIndex&&finder.message?<p className={`mt-2 text-xs ${finder.status==="error"?"text-rose-300":"text-slate-300"}`}>{finder.message}</p>:null}{finder.stageIndex===stageIndex&&finder.candidates.length?<div className="mt-4 space-y-3">{finder.candidates.map((candidate,index)=><article key={`${candidate.url}-${index}`} className="rounded-xl border border-white/10 bg-slate-950/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="font-semibold text-white">{candidate.title}</h4><p className="mt-1 text-xs text-slate-400">{candidate.provider} · {candidate.authorityTier} · {candidate.resourceType}</p></div><button type="button" onClick={()=>approveCandidate(stageIndex,candidate)} className="btn-primary min-h-11">Approve & add</button></div><p className="mt-2 text-sm text-slate-300">{candidate.whyUseful}</p><p className="mt-2 break-all text-xs text-cyan-300">{candidate.url}</p>{candidate.directYouTube?<p className="mt-2 rounded-lg bg-amber-400/10 p-2 text-xs text-amber-200">Direct YouTube link — last-resort source. Publication quality gate may block it.</p>:null}</article>)}</div>:null}</div>
      <div className="mt-5"><div className="flex items-center justify-between"><h4 className="font-semibold text-white">Learning resources</h4><button type="button" onClick={()=>addResource(stageIndex)} className="text-sm font-semibold text-cyan-300">+ Add resource manually</button></div><div className="mt-3 space-y-3">{(stage.resources??[]).map((resource:any,resourceIndex:number)=><article key={resource.id??resourceIndex} className="rounded-xl border border-white/10 p-4"><div className="mb-3 flex justify-end gap-2"><button type="button" disabled={resourceIndex===0} onClick={()=>moveResource(stageIndex,resourceIndex,-1)} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-30">↑</button><button type="button" disabled={resourceIndex===(stage.resources?.length??0)-1} onClick={()=>moveResource(stageIndex,resourceIndex,1)} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-30">↓</button><button type="button" onClick={()=>removeResource(stageIndex,resourceIndex)} className="rounded-lg border border-rose-300/20 px-3 py-2 text-xs text-rose-200">Delete</button></div><div className="grid gap-3 md:grid-cols-2"><Field label="Title"><input className={inputClass} value={resource.title??""} onChange={e=>patchResource(stageIndex,resourceIndex,"title",e.target.value)}/></Field><Field label="Provider"><input className={inputClass} value={resource.provider??""} onChange={e=>patchResource(stageIndex,resourceIndex,"provider",e.target.value)}/></Field><Field label="Type"><select className={inputClass} value={resource.type??"Course"} onChange={e=>patchResource(stageIndex,resourceIndex,"type",e.target.value)}>{["Video","Article","Course","Learning Path","Documentation","Practice","Exam"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Priority"><select className={inputClass} value={resource.priority??"Recommended"} onChange={e=>patchResource(stageIndex,resourceIndex,"priority",e.target.value)}>{["Essential","Recommended","Optional"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Cost"><select className={inputClass} value={resource.cost??"Free"} onChange={e=>patchResource(stageIndex,resourceIndex,"cost",e.target.value)}>{["Free","Paid","Free/Paid"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Estimated time"><input className={inputClass} value={resource.estimatedTime??""} onChange={e=>patchResource(stageIndex,resourceIndex,"estimatedTime",e.target.value)}/></Field></div><Field label="URL"><input className={inputClass} value={resource.url??""} onChange={e=>patchResource(stageIndex,resourceIndex,"url",e.target.value)}/></Field><Field label="Why useful"><textarea rows={3} className={textareaClass} value={resource.whyUseful??""} onChange={e=>patchResource(stageIndex,resourceIndex,"whyUseful",e.target.value)}/></Field>{isDirectYouTube(resource.url)?<p className="mt-2 text-xs text-amber-200">Direct YouTube resource detected.</p>:null}</article>)}</div></div>
      <AssessmentSummary stage={stage}/>
    </section>)}
  </form>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-3 block text-sm text-slate-300">{label}{children}</label>}
function AssessmentSummary({stage}:{stage:any}){const topics=stage.topicAssessments??[],exam=stage.phaseExam;return <div className="mt-5 rounded-xl border border-white/10 p-4"><h4 className="font-semibold text-white">Assessments</h4><p className="mt-2 text-sm text-slate-400">{topics.length} topic assessments · {exam?.questions?.length??0} comprehensive questions. Structured assessment editing and AI generation are the next module.</p></div>}
function normalizeType(value:string){const allowed=["Video","Article","Course","Learning Path","Documentation","Practice","Exam"];return allowed.includes(value)?value:"Course"}
function normalizeCost(value:string){return value==="Paid"||value==="Free/Paid"?value:"Free"}
function isDirectYouTube(url:string){try{const host=new URL(url).hostname.replace(/^www\./,"").toLowerCase();return host==="youtube.com"||host.endsWith(".youtube.com")||host==="youtu.be"}catch{return false}}
