import { saveMappingAction,saveOccupationAction,saveRoadmapLinkAction,setOccupationArchivedAction } from "@/app/admin/(studio)/occupations/actions";
import type { OccupationFamilyRow } from "@/lib/admin/occupationRepository";
import { OCCUPATION_COUNTRIES } from "@/lib/intelligence/occupationDomain";
const join=(values?:string[])=>values?.join("\n")??"";
export function OccupationForm({family}:{family?:OccupationFamilyRow}){return <form action={saveOccupationAction} className="grid max-w-4xl gap-4 sm:grid-cols-2"><input type="hidden" name="id" value={family?.id??""}/><Field label="Slug" name="slug" value={family?.slug} disabled={Boolean(family)} required/><Field label="Name" name="name" value={family?.name} required/><Field label="Short name" name="shortName" value={family?.short_name} required/><Field label="Mapping version" name="mappingVersion" value={family?.mapping_version??"1.0.0"} required/><Area label="Description" name="description" value={family?.description} required/><Area label="Classification scope" name="classificationScope" value={family?.classification_scope} required/><Area label="Aliases — one per line" name="aliases" value={join(family?.aliases)}/><Area label="Included occupations — one per line" name="includedOccupations" value={join(family?.included_occupations)}/><Area label="Excluded occupations — one per line" name="excludedOccupations" value={join(family?.excluded_occupations)}/><Area label="Methodology summary" name="methodologySummary" value={family?.methodology_summary} required/><div className="sm:col-span-2"><button className="btn-primary">Save occupation family</button></div></form>}
export function MappingForm({familyId,mappingVersion}:{familyId:string;mappingVersion:string}){return <form action={saveMappingAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="occupationFamilyId" value={familyId}/><Select label="Country" name="countryCode" options={OCCUPATION_COUNTRIES.map(code=>[code,code.toUpperCase()])}/><Field label="Classification system" name="classificationSystem" required/><Field label="Official occupation code" name="occupationCode" required/><Field label="Official occupation title" name="occupationTitle" required/><Select label="Relevance" name="relevanceLevel" options={[["primary","Primary"],["related","Related"],["adjacent","Adjacent"]]}/><Field label="Weight (0–1)" name="weight" type="number" step="0.01" value="1" required/><Select label="Mapping confidence" name="mappingConfidence" options={[["low","Low"],["moderate","Moderate"],["high","High"]]}/><Select label="Review status" name="reviewStatus" options={[["draft","Draft"],["under-review","Under review"],["approved","Approved"],["rejected","Rejected"]]}/><Field label="Mapping version" name="mappingVersion" value={mappingVersion} required/><Area label="Inclusion reason" name="inclusionReason" required/><Area label="Exclusions — one per line" name="exclusions"/><Area label="Official evidence URLs — one per line" name="evidenceUrls"/><Area label="Private Admin notes" name="notes"/><div className="sm:col-span-2"><button className="btn-primary">Save mapping</button></div></form>}
export function RoadmapLinkForm({familyId}:{familyId:string}){return <form action={saveRoadmapLinkAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="occupationFamilyId" value={familyId}/><Field label="Career slug" name="careerSlug" required/><Select label="Relationship" name="relationshipType" options={[["primary-roadmap","Primary roadmap"],["related-roadmap","Related roadmap"],["adjacent-roadmap","Adjacent roadmap"]]}/><Field label="Priority" name="priority" type="number" value="100" required/><Select label="Status" name="status" options={[["active","Active"],["inactive","Inactive"]]}/><div className="sm:col-span-2"><button className="btn-secondary">Save roadmap link</button></div></form>}
export function ArchiveOccupation({id,archived}:{id:string;archived:boolean}){return <form action={setOccupationArchivedAction}><input type="hidden" name="id" value={id}/><input type="hidden" name="archived" value={String(!archived)}/><button className="btn-secondary">{archived?"Restore as draft":"Archive occupation family"}</button></form>}
function Field({label,name,value,type="text",step,required,disabled}:{label:string;name:string;value?:string;type?:string;step?:string;required?:boolean;disabled?:boolean}){return <label className="text-sm text-slate-300">{label}<input className="input-field mt-1 w-full" name={name} type={type} step={step} defaultValue={value} required={required} disabled={disabled}/>{disabled?<input type="hidden" name={name} value={value}/>:null}</label>}
function Area({label,name,value,required}:{label:string;name:string;value?:string;required?:boolean}){return <label className="text-sm text-slate-300">{label}<textarea className="input-field mt-1 min-h-24 w-full" name={name} defaultValue={value} required={required}/></label>}
function Select({label,name,options}:{label:string;name:string;options:readonly (readonly string[])[]}){return <label className="text-sm text-slate-300">{label}<select className="input-field mt-1 w-full" name={name}>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>}
