"use client";
import { useMemo,useState } from "react";
import type { CareerWorkspaceData } from "@/types/careerWorkspace";

type Draft={projects:Array<{title:string;difficulty:"Beginner"|"Intermediate"|"Advanced";estimatedTime:string;phaseId:string;description:string;deliverables:string[];skills:string[]}>;portfolioTasks:Array<{title:string;description:string;type:"portfolio"}>;finalChallenge:{title:string;description:string;requirements:string[];deliverables:string[];evaluation:string[]};qualityNotes:string[]};
type Workspace=CareerWorkspaceData;
const input="input-field mt-1 min-h-11 w-full";
const area="input-field mt-1 w-full resize-y";

export default function ProjectPortfolioStudio({careerId,data,action}:{careerId:string;data:Workspace;action:(formData:FormData)=>void}){
  const[workspace,setWorkspace]=useState<Workspace>(()=>structuredClone(data));
  const[ai,setAI]=useState<{status:"idle"|"working"|"ready"|"error";message?:string;draft?:Draft}>({status:"idle"});
  const serialized=useMemo(()=>JSON.stringify(workspace),[workspace]);
  function commit(next:Workspace){setWorkspace(next)}
  function patchProject(index:number,key:string,value:unknown){const next=structuredClone(workspace) as any;next.projects[index]={...next.projects[index],[key]:value};commit(next)}
  function patchPortfolio(index:number,key:string,value:unknown){const next=structuredClone(workspace) as any;next.portfolioTasks[index]={...next.portfolioTasks[index],[key]:value};commit(next)}
  function patchChallenge(key:string,value:unknown){const next=structuredClone(workspace) as any;next.finalChallenge={...next.finalChallenge,[key]:value};commit(next)}
  function addProject(){const next=structuredClone(workspace);next.projects.push({id:`project-${Date.now()}`,title:"New project",difficulty:"Intermediate",estimatedTime:"",phaseId:next.roadmap[0]?.id??"phase-1",description:"",deliverables:[],skills:[]});commit(next)}
  function removeProject(index:number){const next=structuredClone(workspace);next.projects.splice(index,1);commit(next)}
  function moveProject(index:number,dir:-1|1){const next=structuredClone(workspace);const target=index+dir;if(target<0||target>=next.projects.length)return;[next.projects[index],next.projects[target]]=[next.projects[target],next.projects[index]];commit(next)}
  function addPortfolio(){const next=structuredClone(workspace);next.portfolioTasks.push({id:`portfolio-${Date.now()}`,title:"New portfolio task",description:"",type:"portfolio"});commit(next)}
  function removePortfolio(index:number){const next=structuredClone(workspace);next.portfolioTasks.splice(index,1);commit(next)}
  async function generate(){if(ai.status==="working")return;setAI({status:"working",message:"Generating role-specific projects and final challenge…"});try{const response=await fetch("/api/admin/ai/project-portfolio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({careerId})});const body=await response.json() as {draft?:Draft;message?:string;error?:string};if(!response.ok||!body.draft)throw new Error(body.message||body.error||"AI generation failed.");setAI({status:"ready",message:"Draft generated. Review before applying.",draft:body.draft})}catch(error){setAI({status:"error",message:error instanceof Error?error.message:"AI generation failed."})}}
  function applyDraft(){const draft=ai.draft;if(!draft)return;const next=structuredClone(workspace);next.projects=draft.projects.map((p,index)=>({id:`project-${index+1}`,title:p.title,difficulty:p.difficulty,estimatedTime:p.estimatedTime,phaseId:p.phaseId||next.roadmap[Math.min(index,next.roadmap.length-1)]?.id||"phase-1",description:p.description,deliverables:p.deliverables,skills:p.skills}));next.portfolioTasks=draft.portfolioTasks.map((task,index)=>({id:`portfolio-${index+1}`,title:task.title,description:task.description,type:"portfolio"}));next.finalChallenge=draft.finalChallenge;commit(next);setAI(current=>({...current,message:"AI draft applied to the working content. Review and save before publication."}))}
  return <form action={action} className="space-y-5"><input type="hidden" name="id" value={careerId}/><input type="hidden" name="workspaceData" value={serialized}/>
    <section className="rounded-2xl border border-cyan-300/15 bg-cyan-400/5 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold text-white">AI Project & Portfolio Copilot</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-400">Generates role-specific projects, portfolio tasks and a final challenge from the saved Career structure. AI cannot publish or add external claims.</p></div><div className="flex gap-2"><button type="button" disabled={ai.status==="working"} onClick={()=>void generate()} className="btn-secondary min-h-11 disabled:opacity-50">{ai.status==="working"?"Generating…":"Generate with AI"}</button>{ai.draft?<button type="button" onClick={applyDraft} className="btn-primary min-h-11">Apply draft</button>:null}</div></div>{ai.message?<p className={`mt-3 text-xs ${ai.status==="error"?"text-rose-300":"text-slate-300"}`}>{ai.message}</p>:null}{ai.draft?.qualityNotes?.length?<ul className="mt-3 list-disc pl-5 text-xs text-amber-100">{ai.draft.qualityNotes.map(note=><li key={note}>{note}</li>)}</ul>:null}</section>

    <Section title="Projects" description="Build progressive, job-relevant portfolio projects."><div className="space-y-3">{workspace.projects.map((project,index)=><article key={project.id} className="rounded-xl border border-white/10 bg-white/[.02] p-4"><div className="mb-3 flex justify-end gap-2"><button type="button" disabled={index===0} onClick={()=>moveProject(index,-1)} className="btn-secondary min-h-10">↑</button><button type="button" disabled={index===workspace.projects.length-1} onClick={()=>moveProject(index,1)} className="btn-secondary min-h-10">↓</button><button type="button" onClick={()=>removeProject(index)} className="btn-secondary min-h-10">Delete</button></div><div className="grid gap-3 md:grid-cols-3"><Field label="Title"><input className={input} value={project.title} onChange={e=>patchProject(index,"title",e.target.value)}/></Field><Field label="Difficulty"><select className={input} value={project.difficulty} onChange={e=>patchProject(index,"difficulty",e.target.value)}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></Field><Field label="Estimated time"><input className={input} value={project.estimatedTime} onChange={e=>patchProject(index,"estimatedTime",e.target.value)}/></Field></div><Field label="Roadmap phase"><select className={input} value={project.phaseId} onChange={e=>patchProject(index,"phaseId",e.target.value)}>{workspace.roadmap.map(phase=><option key={phase.id} value={phase.id}>{phase.title}</option>)}</select></Field><Field label="Description"><textarea rows={4} className={area} value={project.description} onChange={e=>patchProject(index,"description",e.target.value)}/></Field><ListEditor label="Deliverables" values={project.deliverables} onChange={value=>patchProject(index,"deliverables",value)}/><ListEditor label="Skills" values={project.skills} onChange={value=>patchProject(index,"skills",value)}/></article>)}</div><button type="button" onClick={addProject} className="btn-secondary mt-4 min-h-11">+ Add project</button></Section>

    <Section title="Portfolio tasks" description="Tasks that convert completed work into employer-facing proof."><div className="space-y-3">{workspace.portfolioTasks.map((task,index)=><article key={task.id} className="rounded-xl border border-white/10 p-4"><div className="flex justify-end"><button type="button" onClick={()=>removePortfolio(index)} className="btn-secondary min-h-10">Delete</button></div><Field label="Title"><input className={input} value={task.title} onChange={e=>patchPortfolio(index,"title",e.target.value)}/></Field><Field label="Description"><textarea rows={3} className={area} value={task.description} onChange={e=>patchPortfolio(index,"description",e.target.value)}/></Field></article>)}</div><button type="button" onClick={addPortfolio} className="btn-secondary mt-4 min-h-11">+ Add portfolio task</button></Section>

    <Section title="Final challenge" description="Capstone proof that integrates the Career's core capabilities."><Field label="Title"><input className={input} value={workspace.finalChallenge.title} onChange={e=>patchChallenge("title",e.target.value)}/></Field><Field label="Description"><textarea rows={4} className={area} value={workspace.finalChallenge.description} onChange={e=>patchChallenge("description",e.target.value)}/></Field><ListEditor label="Requirements" values={workspace.finalChallenge.requirements} onChange={value=>patchChallenge("requirements",value)}/><ListEditor label="Deliverables" values={workspace.finalChallenge.deliverables} onChange={value=>patchChallenge("deliverables",value)}/><ListEditor label="Evaluation criteria" values={workspace.finalChallenge.evaluation} onChange={value=>patchChallenge("evaluation",value)}/></Section>
    <div className="flex justify-end"><button className="btn-primary min-h-12">Validate & save</button></div>
  </form>
}
function Section({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border border-white/10 bg-white/[.025] p-5"><div><h3 className="font-semibold text-white">{title}</h3><p className="mt-1 text-xs text-slate-500">{description}</p></div>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm text-slate-300">{label}{children}</label>}
function ListEditor({label,values,onChange}:{label:string;values:string[];onChange:(values:string[])=>void}){return <div><div className="flex justify-between"><p className="text-sm text-slate-300">{label}</p><button type="button" onClick={()=>onChange([...values,""])} className="text-xs font-semibold text-cyan-300">+ Add</button></div><div className="mt-2 space-y-2">{values.map((value,index)=><div className="flex gap-2" key={index}><input className={input} value={value} onChange={e=>onChange(values.map((item,i)=>i===index?e.target.value:item))}/><button type="button" onClick={()=>onChange(values.filter((_,i)=>i!==index))} className="btn-secondary min-h-11">×</button></div>)}</div></div>}
