"use client";
import dynamic from "next/dynamic"; import { usePathname,useRouter,useSearchParams } from "next/navigation"; import { useEffect,useState } from "react"; import { useReducedMotion } from "framer-motion"; import type { CareerWorkspaceData } from "@/types/careerWorkspace"; import type { IntelligenceFilters } from "@/types/careerIntelligence"; import { defaultIntelligenceFilters } from "@/lib/intelligence/careerIntelligenceService"; import { listIntelligenceSources } from "@/lib/intelligence/sourceResolver"; import countryRegistry from "../../../../content/intelligence/country-registry.json";
const load=(name:string)=>dynamic(()=>import("./sections/IntelligenceSections").then(module=>module[name as keyof typeof module] as React.ComponentType<{career:CareerWorkspaceData;filters:IntelligenceFilters}>),{loading:()=> <div role="status" className="p-6 text-sm text-slate-400">Loading section…</div>,ssr:false});
const MarketSnapshot=load("MarketSnapshotSection"),Demand=load("DemandTrendsSection"),WorkModel=load("WorkModelSection"),Salary=load("SalarySection"),Skills=load("SkillsSection"),Locations=load("LocationsSection"),Mobility=load("MobilitySection"),CV=load("LocalCVSection"),Outlook=load("OutlookSection"),Methodology=load("MethodologySection");
const sectionDefinitions=[
 {id:"snapshot",icon:"◉",title:"Market Snapshot",description:"A concise view of verified sample evidence and broad provider context.",status:"Baseline snapshot",component:MarketSnapshot},
 {id:"demand",icon:"↗",title:"Demand & Hiring Trends",description:"Understand current hiring activity and comparable historical growth.",status:"Baseline only",component:Demand},
 {id:"work-model",icon:"⌂",title:"Work Model",description:"Review explicit Remote, Hybrid, On-site, and unclassified evidence.",status:"Evidence coverage",component:WorkModel},
 {id:"salary",icon:"¤",title:"Salary Intelligence",description:"Compare validated listing salary evidence separately from broad provider context.",status:"Salary evidence",component:Salary},
 {id:"skills",icon:"◇",title:"Skills & Employer Expectations",description:"Separate Learning content from market-derived skill evidence.",status:"Insufficient text evidence",component:Skills},
 {id:"locations",icon:"◎",title:"Locations & Country Comparison",description:"Compare verified matches inside independently published country samples.",status:"3 published markets",component:Locations},
 {id:"mobility",icon:"✦",title:"Global Mobility & Immigration",description:"Review country-specific official evidence and provisional occupation proxies.",status:"Official sources",component:Mobility},
 {id:"cv",icon:"▤",title:"CV Role Alignment",description:"Run private local CV analysis without uploading or storing your file.",status:"Available locally",component:CV},
 {id:"outlook",icon:"⌁",title:"Future Outlook",description:"Separate official projections, direct trends, proxies, and uncertainty.",status:"Insufficient coverage",component:Outlook},
 {id:"methodology",icon:"ⓘ",title:"Sources & Methodology",description:"Inspect sources, coverage, licenses, mappings, and known limitations.",status:"Verified registry",component:Methodology},
] as const;
export default function CareerIntelligenceWorkspace({career}:{career:CareerWorkspaceData}){const router=useRouter(),pathname=usePathname(),searchParams=useSearchParams(),reduceMotion=useReducedMotion();const requested=searchParams.get("section");const openId=sectionDefinitions.some(item=>item.id===requested)?requested:null;const [filters,setFilters]=useState<IntelligenceFilters>({...defaultIntelligenceFilters,country:"gb",currency:"GBP"});const [showFilters,setShowFilters]=useState(false),[snapshotState,setSnapshotState]=useState<"loading"|"published"|"empty">("loading");const sources=listIntelligenceSources(),official=sources.filter(source=>source.reliabilityTier==="official"&&source.status==="active");useEffect(()=>{const controller=new AbortController();setSnapshotState("loading");fetch(`/api/career-intelligence/snapshots?career=${encodeURIComponent(career.slug)}&country=${filters.country}&type=market`,{signal:controller.signal}).then(response=>response.json()).then(body=>setSnapshotState(body.snapshot?.status==="published"?"published":"empty")).catch(error=>{if(error.name!=="AbortError")setSnapshotState("empty")});return()=>controller.abort()},[career.slug,filters.country]);function toggle(id:string){const next=openId===id?null:id;const params=new URLSearchParams(searchParams.toString());if(next)params.set("section",next);else params.delete("section");router.push(`${pathname}${params.size?`?${params}`:""}`,{scroll:false});if(next)window.setTimeout(()=>document.getElementById(`intelligence-header-${next}`)?.scrollIntoView({behavior:reduceMotion?"auto":"smooth",block:"start"}),reduceMotion?0:210)}return <section className="box-border h-full w-full min-w-0 max-w-full overflow-x-hidden overflow-y-auto px-4 pb-28 pt-5 text-slate-200 lg:px-8 lg:pb-8">
 <header className="mx-auto max-w-6xl"><div className="rounded-3xl bg-[radial-gradient(circle_at_15%_0%,rgba(8,145,178,.18),transparent_42%),rgba(2,6,23,.82)] p-5 sm:p-7"><p className="eyebrow">{career.title} · Research dossier</p><h1 className="mt-3 font-display text-3xl font-semibold text-white sm:text-5xl">Career Intelligence</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Explore verified market evidence, mobility references, and private role alignment without fabricated statistics.</p></div>
 <div className="mt-3 grid gap-2 rounded-2xl border border-white/10 bg-slate-950/70 p-3 text-xs sm:grid-cols-4"><Coverage label="Data source" value="Adzuna"/><Coverage label="Snapshot state" value={snapshotState==="published"?"Published snapshot available":snapshotState==="loading"?"Checking snapshots":"Awaiting first snapshot"}/><Coverage label="Configured countries" value={String(countryRegistry.filter(item=>item.configured).length)}/><Coverage label="Unavailable" value="Skills · Forecast"/></div>
 <div className="mt-3 flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-slate-400">Target: {filters.country.toUpperCase()} · All seniorities · {filters.currency}</p><button type="button" aria-expanded={showFilters} aria-controls="intelligence-filters" onClick={()=>setShowFilters(value=>!value)} className="min-h-11 rounded-xl border border-white/10 px-4 text-xs font-semibold text-white">Filters {showFilters?"↑":"↓"}</button></div>
 {showFilters?<div id="intelligence-filters" className="mt-2 grid gap-3 rounded-2xl border border-white/10 bg-slate-950/80 p-4 sm:grid-cols-2"><Select label="Country" value={filters.country} onChange={country=>{const selected=countryRegistry.find(item=>item.productCode===country);setFilters(current=>({...current,country,currency:selected?.currencyCode??current.currency}))}} options={countryRegistry.filter(item=>item.configured).map(item=>[item.productCode,item.name])}/><Select label="Seniority" value={filters.seniority} onChange={seniority=>setFilters(current=>({...current,seniority}))} options={[["All levels","All levels"],["Junior","Junior"],["Mid-level","Mid-level"],["Senior","Senior"]]}/></div>:null}
 </header>
 <div className="mx-auto mt-5 max-w-6xl space-y-2">{sectionDefinitions.map((definition,index)=>{const open=openId===definition.id;const Component=definition.component,status=snapshotState==="published"?definition.status:"Awaiting first snapshot";return <article key={definition.id} className={`overflow-hidden rounded-2xl border transition-colors ${open?"border-cyan-300/25 bg-slate-950/90":"border-white/10 bg-slate-950/60"}`}><h2><button id={`intelligence-header-${definition.id}`} type="button" aria-expanded={open} aria-controls={`intelligence-panel-${definition.id}`} onClick={()=>toggle(definition.id)} className="flex min-h-[76px] w-full scroll-mt-5 items-center gap-3 px-4 py-3 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-300 sm:px-5"><span aria-hidden="true" className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-cyan-400/5 text-cyan-300">{definition.icon}</span><span className="min-w-0 flex-1"><span className="block font-semibold text-white">{index+1}. {definition.title}</span><span className="mt-1 block text-xs leading-5 text-slate-400">{definition.description}</span></span><span className="hidden shrink-0 rounded-full border border-white/10 px-3 py-1 text-[10px] font-semibold uppercase tracking-wide text-slate-400 sm:block">{status}</span><span aria-hidden="true" className={`shrink-0 text-lg text-slate-400 transition-transform duration-200 ${open?"rotate-180":""}`}>⌄</span></button></h2>{open?<div id={`intelligence-panel-${definition.id}`} role="region" aria-labelledby={`intelligence-header-${definition.id}`} className="border-t border-white/10 p-4 sm:p-5" style={{animationDuration:reduceMotion?"0ms":"210ms"}}><Component career={career} filters={filters}/></div>:null}</article>})}</div>
 </section>}
function Coverage({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white/[.025] p-3"><span className="text-slate-500">{label}</span><strong className="mt-1 block font-semibold text-slate-200">{value}</strong></div>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[][]}){return <label className="text-xs text-slate-400">{label}<select className="input-field mt-1 min-h-11" value={value} onChange={event=>onChange(event.target.value)}>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}
