export type IntelligenceReliability = "official" | "high" | "moderate" | "low" | "unverified";
export type IntelligenceAvailability = "available" | "not-configured" | "insufficient-data" | "stale" | "error";
export type WorkModel = "remote" | "hybrid" | "onsite" | "not-specified";
export type SalaryType = "base" | "bonus" | "equity" | "total-compensation" | "contract-rate";

export interface IntelligenceEvidence { sourceIds: string[]; coverage: string; sampleSize?: number; observationPeriod?: string; calculatedAt?: string; methodology: string; reliability: IntelligenceReliability; warnings: string[] }
export interface WorkModelDistribution { remote: number; hybrid: number; onsite: number; notSpecified: number; explicitSampleSize: number; totalSampleSize: number }
export interface CareerMarketSnapshot { careerId: string; geography: string; seniority: string; timePeriod: string; activePostings?: number; newPostings?: number; previousPeriodChange?: number; yearOverYearChange?: number; workModelDistribution?: WorkModelDistribution; evidence: IntelligenceEvidence; availability: IntelligenceAvailability }
export interface SalarySnapshot { careerId: string; country: string; city?: string; seniority: string; currency: string; salaryPeriod: "annual"|"monthly"|"hourly"; salaryType: SalaryType; median?: number; percentile25?: number; percentile75?: number; minimum?: number; maximum?: number; sampleSize?: number; sourceIds: string[]; observationPeriod?: string; conversionDate?: string; calculatedAt?: string; availability: IntelligenceAvailability }
export interface SkillDemandSnapshot { careerId: string; skillId: string; postingCount?: number; postingShare?: number; trend?: number; seniority: string; geography: string; salaryRelationship?: string; sourceIds: string[]; availability: IntelligenceAvailability; roadmapStepId?: string }
export interface OccupationCodeMapping { system: "ISCO"|"ESCO"|"SOC"|"NOC"|"ANZSCO"|string; code?: string; mappedTitle?: string; confidence: number; sourceId: string; humanReviewed: boolean }
export interface MobilityCountryProfile { careerId: string; country: string; occupationCodes: OccupationCodeMapping[]; shortageStatus: "listed"|"not-listed"|"unknown"; sponsorshipSignals?: number; workAuthorizationRestrictions: string[]; qualificationRequirements: string[]; languageRequirements: string[]; officialPathways: string[]; accessibilityIndicators: Array<{label:string; value:string; sourceId?:string}>; confidence: IntelligenceReliability; sourceIds: string[]; effectiveDate?: string; lastVerifiedAt?: string; availability: IntelligenceAvailability }
export interface IntelligenceFilters { country: string; region: string; city: string; experienceLevel: string; seniority: string; employmentType: string; workModel: string; industry: string; timePeriod: string; currency: string; salaryType: string; compareCountries: string[] }
export interface CareerIntelligenceResult { market: CareerMarketSnapshot; salaries: SalarySnapshot[]; skills: SkillDemandSnapshot[]; mobility: MobilityCountryProfile[]; forecast: { availability: IntelligenceAvailability; methodology: string; uncertainty: string; sourceIds: string[] }; warnings: string[] }
