import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { safeExternalUrl } from "@/lib/job-agent/normalization";
import { approveApplicationPack, beginManualSubmission, confirmManualSubmission, prepareApplication, updateApplicationStatus } from "../../applicationActions";

type Asset = { id: string; asset_type: string; version: string; structured_content: Record<string, unknown> | null; created_at: string };
type Grounded = { text?: string; evidenceIds?: string[] };

function groundedList(value: unknown) {
  return Array.isArray(value) ? value.filter((item): item is Grounded => Boolean(item && typeof item === "object")) : [];
}

export default async function ApplicationPackPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ generated?: string; approved?: string; manual?: string; submitted?: string; status_updated?: string; error?: string }> }) {
  const user = await requireUser("/job-agent");
  const { id } = await params;
  const query = await searchParams;
  const supabase = await createClient();
  const [applicationResult, assetsResult, readinessResult, eventsResult] = await Promise.all([
    supabase.from("applications").select("id,job_id,status,agent_mode,execution_capability,submission_receipt,submitted_at,follow_up_due_at,next_action,continuation_url,notes,created_at,job_opportunities(id,company,role,location,job_url,application_url,source_url,fit_score,fit_confidence,eligibility_status,eligibility_reasons,verification_status,execution_capability,source,founder_positioning,status,recommendation,skip_reason,freshness_status)").eq("id", id).eq("user_id", user.id).maybeSingle(),
    supabase.from("application_assets").select("id,asset_type,version,structured_content,created_at").eq("application_id", id).eq("user_id", user.id).order("created_at", { ascending: false }).returns<Asset[]>(),
    supabase.from("job_application_readiness").select("status,checklist,missing_inputs,assessed_at").eq("user_id", user.id).eq("job_id", (await supabase.from("applications").select("job_id").eq("id", id).eq("user_id", user.id).maybeSingle<{ job_id: string }>()).data?.job_id ?? "00000000-0000-0000-0000-000000000000").maybeSingle(),
    supabase.from("application_status_events").select("from_status,to_status,reason_code,created_at").eq("user_id", user.id).eq("application_id", id).order("created_at", { ascending: false }).limit(12),
  ]);
  if (!applicationResult.data || applicationResult.error) notFound();
  const application = applicationResult.data;
  const rawJob = application.job_opportunities;
  const job = Array.isArray(rawJob) ? rawJob[0] : rawJob;
  const stale = job?.eligibility_status === "blocked" || job?.freshness_status === "expired";
  const assets = assetsResult.data ?? [];
  const latest = new Map<string, Asset>();
  for (const asset of assets) if (!latest.has(asset.asset_type)) latest.set(asset.asset_type, asset);
  const cv = latest.get("cv")?.structured_content ?? {};
  const portfolio = latest.get("portfolio")?.structured_content ?? {};
  const cover = latest.get("cover_note")?.structured_content ?? {};
  const screening = latest.get("screening_answers")?.structured_content ?? {};
  const summary = cv.professionalSummary as Grounded | undefined;
  const applicationSummary = cv.applicationSummary as Grounded | undefined;
  const skills = groundedList(cv.selectedSkills);
  const keyAchievements = groundedList(cv.keyAchievements);
  const highlights = groundedList(cv.highlights);
  const cases = Array.isArray(portfolio.cases) ? portfolio.cases as Array<{ title?: string; framing?: string; relevance?: Grounded }> : [];
  const paragraphs = groundedList(cover.paragraphs);
  const recruiterMessage = cover.recruiterMessage as Grounded | undefined;
  const answers = Array.isArray(screening.answers) ? screening.answers as Array<{ question?: string; answer?: string | null; requiresUserDecision?: boolean }> : [];
  const missing = Array.isArray(screening.missingUserDecisions) ? screening.missingUserDecisions.map(String) : [];
  const hasPack = Boolean(summary?.text || skills.length || highlights.length || cases.length || paragraphs.length || answers.length);
  const manualApplicationUrl = safeExternalUrl(application.continuation_url ?? job?.application_url ?? job?.job_url);

  return <main className="mx-auto max-w-5xl px-5 py-10 sm:py-12">
    <Link href="/job-agent" className="text-sm font-semibold text-violet-300">← Job Agent</Link>
    {query.generated ? <p role="status" className="mt-5 rounded-xl border border-emerald-300/20 bg-emerald-400/10 p-3 text-sm text-emerald-100">Grounded application pack generated. Review it before using it.</p> : null}
    {query.approved ? <p role="status" className="mt-5 rounded-xl border border-cyan-300/20 bg-cyan-400/10 p-3 text-sm text-cyan-100">Pack approved. The system still requires the external manual action and submission evidence.</p> : null}
    {query.manual ? <p role="status" className="mt-5 rounded-xl border border-amber-300/20 bg-amber-400/10 p-3 text-sm text-amber-100">Manual submission started. Complete the official form, then return here to record the result.</p> : null}
    {query.submitted ? <p role="status" className="mt-5 rounded-xl border border-emerald-300/20 bg-emerald-400/10 p-3 text-sm text-emerald-100">Submission recorded from your explicit confirmation. It was not inferred by the Agent.</p> : null}
    {query.status_updated ? <p role="status" className="mt-5 rounded-xl border border-cyan-300/20 bg-cyan-400/10 p-3 text-sm text-cyan-100">Lifecycle updated to {query.status_updated.replaceAll("_", " ")} from your evidence note.</p> : null}
    {query.error ? <p role="alert" className="mt-5 rounded-xl border border-rose-300/20 bg-rose-400/10 p-3 text-sm text-rose-100">The requested transition was rejected: {query.error.replaceAll("-", " ")}.</p> : null}
    <div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Application Pack</p><h1 className="mt-2 font-display text-3xl font-semibold text-white">{job?.role ?? "Application"}</h1><p className="mt-2 text-slate-400">{job?.company ?? "Company"}{job?.location ? ` · ${job.location}` : ""}</p></div><div className="flex items-center gap-3"><span className="rounded-full border border-violet-300/20 bg-violet-400/[.06] px-3 py-1.5 text-xs font-semibold capitalize text-violet-200">{stale ? "historical / not eligible" : String(application.status).replaceAll("_", " ")}</span>{job?.fit_score !== null && job?.fit_score !== undefined ? <span className="text-sm font-semibold text-cyan-200">{job.fit_score}% Fit</span> : null}</div></div>
    {stale ? <div className="mt-6 rounded-2xl border border-rose-300/20 bg-rose-400/[.05] p-4"><p className="text-xs font-semibold uppercase tracking-[.14em] text-rose-200">Application blocked</p><p className="mt-2 text-sm leading-6 text-slate-300">{job?.skip_reason ?? job?.eligibility_reasons?.join(" ") ?? "This vacancy is expired or conflicts with a hard constraint."}</p></div> : application.next_action ? <div className="mt-6 rounded-2xl border border-amber-300/15 bg-amber-400/[.04] p-4"><p className="text-xs font-semibold uppercase tracking-[.14em] text-amber-200">Next action</p><p className="mt-2 text-sm text-slate-300">{application.next_action}</p></div> : null}

    {readinessResult.data ? <section className="mt-6 rounded-2xl border border-white/[.07] bg-white/[.02] p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-white">Application readiness</h2><span className="rounded-full border border-white/10 px-3 py-1 text-xs capitalize text-slate-300">{String(readinessResult.data.status).replaceAll("_", " ")}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{(Array.isArray(readinessResult.data.checklist) ? readinessResult.data.checklist : []).map((check: { key?: string; status?: string; reason?: string }) => <div key={check.key} className="rounded-xl border border-white/[.06] p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{check.key?.replaceAll("_", " ")} · {check.status}</p><p className="mt-1 text-xs leading-5 text-slate-300">{check.reason}</p></div>)}</div></section> : null}

    {applicationSummary?.text ? <section className="mt-6 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.035] p-5"><h2 className="font-semibold text-cyan-100">Application summary</h2><p className="mt-2 text-sm leading-6 text-slate-300">{applicationSummary.text}</p><p className="mt-2 text-[11px] text-slate-600">Evidence: {applicationSummary.evidenceIds?.join(", ")}</p></section> : null}

    <div className="mt-7 grid gap-6 lg:grid-cols-2">
      <section className="glass rounded-2xl border border-white/[.07] p-5"><h2 className="font-display text-xl font-semibold text-white">Tailored CV content</h2>{summary?.text ? <div className="mt-4"><p className="text-xs uppercase tracking-[.14em] text-slate-500">Professional summary</p><p className="mt-2 text-sm leading-6 text-slate-300">{summary.text}</p></div> : null}{skills.length ? <div className="mt-4 flex flex-wrap gap-2">{skills.map((skill, index) => <span key={`${skill.text}-${index}`} className="rounded-full bg-cyan-400/[.07] px-2.5 py-1 text-xs text-cyan-100">{skill.text}</span>)}</div> : null}<div className="mt-5 space-y-3">{[...keyAchievements, ...highlights].map((item, index) => <div key={`${item.text}-${index}`} className="rounded-xl border border-white/[.06] p-3"><p className="text-sm leading-6 text-slate-300">{item.text}</p><p className="mt-2 text-[11px] text-slate-600">Evidence: {item.evidenceIds?.join(", ")}</p></div>)}</div>{!hasPack ? <p className="mt-4 text-sm text-slate-500">No generated CV content is stored for this application.</p> : null}</section>
      <section className="glass rounded-2xl border border-white/[.07] p-5"><h2 className="font-display text-xl font-semibold text-white">Tailored portfolio</h2><div className="mt-4 space-y-3">{cases.length ? cases.map((item, index) => <article key={`${item.title}-${index}`} className="rounded-xl border border-white/[.06] p-4"><div className="flex items-start justify-between gap-3"><p className="font-semibold text-white">{item.title ?? "Case study"}</p><span className="text-xs text-violet-300">{item.framing}</span></div><p className="mt-2 text-sm leading-6 text-slate-300">{item.relevance?.text}</p></article>) : <p className="text-sm text-slate-400">No verified project case was selected from the current canonical evidence.</p>}</div>{job?.founder_positioning ? <p className="mt-4 text-xs leading-5 text-slate-500">Founder positioning: {job.founder_positioning}</p> : null}</section>
      <section className="glass rounded-2xl border border-white/[.07] p-5"><h2 className="font-display text-xl font-semibold text-white">Cover letter & recruiter message</h2><div className="mt-4 space-y-4">{paragraphs.map((item, index) => <p key={index} className="text-sm leading-6 text-slate-300">{item.text}</p>)}{recruiterMessage?.text ? <div className="rounded-xl border border-violet-300/15 bg-violet-400/[.04] p-3"><p className="text-xs font-semibold uppercase tracking-wide text-violet-200">Recruiter message</p><p className="mt-2 text-sm leading-6 text-slate-300">{recruiterMessage.text}</p></div> : null}{!paragraphs.length && !recruiterMessage?.text ? <p className="text-sm text-slate-500">No cover note is stored for this application.</p> : null}</div></section>
      <section className="glass rounded-2xl border border-white/[.07] p-5"><h2 className="font-display text-xl font-semibold text-white">Screening answers</h2><div className="mt-4 space-y-3">{answers.length ? answers.map((item, index) => <div key={index} className="rounded-xl border border-white/[.06] p-3"><p className="text-sm font-semibold text-white">{item.question}</p><p className="mt-1 text-sm text-slate-300">{item.answer ?? "No safe answer available."}</p>{item.requiresUserDecision ? <p className="mt-2 text-xs font-semibold text-amber-200">User decision required</p> : null}</div>) : <p className="text-sm text-slate-400">No screening questions were generated from the available facts.</p>}</div></section>
    </div>

    {missing.length ? <section className="mt-6 rounded-2xl border border-amber-300/15 bg-amber-400/[.035] p-5"><h2 className="font-semibold text-amber-100">Decisions the Agent will not make for you</h2><ul className="mt-3 space-y-2 text-sm text-slate-300">{missing.map((item) => <li key={item}>• {item}</li>)}</ul></section> : null}
    <section className="mt-7 rounded-2xl border border-violet-300/15 bg-violet-400/[.035] p-5"><p className="eyebrow">Safe execution</p><h2 className="mt-1 font-display text-xl font-semibold text-white">{String(application.execution_capability ?? job?.execution_capability ?? "manual_only").replaceAll("_", " ")}</h2><p className="mt-2 text-sm leading-6 text-slate-400">No approved universal auto-submit API is configured for this vacancy. The exact user action is recorded and submission state requires evidence.</p><div className="mt-5 flex flex-wrap gap-3">{stale ? <Link href="/job-agent" className="btn-primary inline-flex min-h-11 items-center justify-center">Find eligible jobs</Link> : !hasPack && job?.id ? <form action={prepareApplication}><input type="hidden" name="job_id" value={job.id} /><button className="btn-primary min-h-11">Retry application pack</button></form> : application.status === "ready_for_review" ? <form action={approveApplicationPack}><input type="hidden" name="application_id" value={application.id} /><button className="btn-primary min-h-11">I reviewed this pack — approve</button></form> : application.status === "ready_for_submit" ? <form action={beginManualSubmission}><input type="hidden" name="application_id" value={application.id} /><button className="btn-primary min-h-11">Start manual submission</button></form> : application.status === "manual_action_required" && manualApplicationUrl ? <a href={manualApplicationUrl} target="_blank" rel="noopener noreferrer" className="btn-primary inline-flex min-h-11 items-center justify-center">Open exact application URL</a> : application.status === "manual_action_required" ? <span className="rounded-xl border border-rose-300/20 px-4 py-2 text-sm text-rose-200">Application URL failed safety validation</span> : null}</div>{application.status === "manual_action_required" ? <form action={confirmManualSubmission} className="mt-5 grid gap-3 rounded-xl border border-amber-300/15 bg-amber-400/[.035] p-4"><input type="hidden" name="application_id" value={application.id} /><label className="text-sm text-slate-300">Submission receipt or confirmation ID (optional)<input name="submission_receipt" className="input-field mt-2 min-h-11 w-full" placeholder="Provider confirmation ID or email reference" /></label><label className="flex items-start gap-3 text-sm leading-6 text-amber-100"><input type="checkbox" name="submission_confirmed" className="mt-1" />I confirm that I personally completed the external submission and the provider accepted it.</label><button className="btn-secondary min-h-11 justify-self-start">Record as submitted</button></form> : null}<p className="mt-4 text-xs leading-5 text-slate-500">Ready for Review means generation succeeded. Submitted means a receipt or your explicit attestation exists; recruiter response is never inferred.</p></section>

    {eventsResult.data?.length ? <section className="mt-6 rounded-2xl border border-white/[.07] p-5"><h2 className="font-semibold text-white">Lifecycle evidence</h2><ol className="mt-3 space-y-2 text-xs text-slate-400">{eventsResult.data.map((event) => <li key={`${event.created_at}-${event.reason_code}`}>{new Date(event.created_at).toLocaleString("en-GB")} · {event.from_status ?? "created"} → {event.to_status} · {event.reason_code}</li>)}</ol></section> : null}
    {["submitted", "applied", "recruiter_response", "interview", "assessment", "offer"].includes(application.status) ? <section className="mt-6 rounded-2xl border border-white/[.07] p-5"><h2 className="font-semibold text-white">Record a real external outcome</h2><p className="mt-2 text-xs leading-5 text-slate-500">The Agent never infers recruiter replies, interviews or offers. Record only an event you can support with an email, ATS status or conversation.</p><form action={updateApplicationStatus} className="mt-4 grid gap-3 sm:grid-cols-[.7fr_1.3fr_auto] sm:items-end"><input type="hidden" name="application_id" value={application.id} /><label className="text-sm text-slate-400">New status<select name="status" className="input-field mt-2 min-h-11 w-full"><option value="recruiter_response">Recruiter response</option><option value="interview">Interview</option><option value="assessment">Assessment</option><option value="offer">Offer</option><option value="rejected">Rejected</option><option value="withdrawn">Withdrawn</option><option value="expired">Expired</option></select></label><label className="text-sm text-slate-400">Evidence note<input name="evidence_note" required className="input-field mt-2 min-h-11 w-full" placeholder="e.g. Recruiter email received 3 Sep" /></label><button className="btn-secondary min-h-11">Record outcome</button></form></section> : null}
  </main>;
}
