"use server";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/admin/adminAuth";
import { saveOccupationFamily,setOccupationArchived,upsertOccupationMapping,upsertOccupationRoadmapLink } from "@/lib/admin/occupationRepository";
import { validateOccupationFamily,validateOccupationMapping,type OccupationFamilyInput,type OccupationMappingInput } from "@/lib/intelligence/occupationDomain";
const list=(value:FormDataEntryValue|null)=>String(value??"").split(/\r?\n|,/).map(item=>item.trim()).filter(Boolean);
async function admin(){const auth=await requireAdmin();if(auth.status!=="admin")throw new Error("ADMIN_REQUIRED");return auth}
export async function saveOccupationAction(formData:FormData){const auth=await admin(),id=String(formData.get("id")??"")||null,value:OccupationFamilyInput={slug:String(formData.get("slug")??""),name:String(formData.get("name")??""),shortName:String(formData.get("shortName")??""),description:String(formData.get("description")??""),classificationScope:String(formData.get("classificationScope")??""),aliases:list(formData.get("aliases")),includedOccupations:list(formData.get("includedOccupations")),excludedOccupations:list(formData.get("excludedOccupations")),methodologySummary:String(formData.get("methodologySummary")??""),mappingVersion:String(formData.get("mappingVersion")??"")},check=validateOccupationFamily(value);if(!check.valid)redirect(`/admin/occupations/${id??"new"}?error=${encodeURIComponent(check.errors.join(" · "))}`);const saved=await saveOccupationFamily(auth.accessToken,id,value);redirect(`/admin/occupations/${saved.id}?saved=family`)}
export async function setOccupationArchivedAction(formData:FormData){const auth=await admin(),id=String(formData.get("id")??""),archived=formData.get("archived")==="true";await setOccupationArchived(auth.accessToken,id,archived);redirect(`/admin/occupations/${id}?saved=${archived?"archived":"restored"}`)}
export async function saveMappingAction(formData:FormData){const auth=await admin(),familyId=String(formData.get("occupationFamilyId")??""),value:OccupationMappingInput={occupationFamilyId:familyId,countryCode:String(formData.get("countryCode")??""),classificationSystem:String(formData.get("classificationSystem")??""),occupationCode:String(formData.get("occupationCode")??""),occupationTitle:String(formData.get("occupationTitle")??""),relevanceLevel:String(formData.get("relevanceLevel")??"") as OccupationMappingInput["relevanceLevel"],weight:Number(formData.get("weight")),inclusionReason:String(formData.get("inclusionReason")??""),exclusions:list(formData.get("exclusions")),mappingConfidence:String(formData.get("mappingConfidence")??"") as OccupationMappingInput["mappingConfidence"],mappingVersion:String(formData.get("mappingVersion")??""),reviewStatus:String(formData.get("reviewStatus")??"") as OccupationMappingInput["reviewStatus"],evidenceUrls:list(formData.get("evidenceUrls")),notes:String(formData.get("notes")??"")},check=validateOccupationMapping(value);if(!check.valid)redirect(`/admin/occupations/${familyId}?error=${encodeURIComponent(check.errors.join(" · "))}`);await upsertOccupationMapping(auth.accessToken,value);redirect(`/admin/occupations/${familyId}?saved=mapping`)}
export async function saveRoadmapLinkAction(formData:FormData){const auth=await admin(),familyId=String(formData.get("occupationFamilyId")??"");await upsertOccupationRoadmapLink(auth.accessToken,{occupationFamilyId:familyId,careerSlug:String(formData.get("careerSlug")??""),relationshipType:String(formData.get("relationshipType")??""),priority:Number(formData.get("priority")),status:String(formData.get("status")??"")});redirect(`/admin/occupations/${familyId}?saved=roadmap-link`)}
