export const FONTS=[{id:'sans',label:'DejaVu Sans',family:'Atelier Sans',file:'DejaVuSans'},{id:'serif',label:'DejaVu Serif',family:'Atelier Serif',file:'DejaVuSerif'},{id:'condensed',label:'DejaVu Sans Condensed',family:'Atelier Condensed',file:'DejaVuSansCondensed'},{id:'editorial',label:'DejaVu Serif Condensed',family:'Atelier Editorial',file:'DejaVuSerifCondensed'},{id:'mono',label:'DejaVu Sans Mono',family:'Atelier Mono',file:'DejaVuSansMono'}];
export const TEMPLATES=[
 {name:'Professional',label:'Professional',description:'Classic rules · single column',layout:'single',accent:'#234b55',header:'plain',heading:'rule',font:'sans',size:9.5,margin:42},
 {name:'Modern',label:'Nordic Sidebar',description:'Skills rail · two columns',layout:'sidebar-left',accent:'#344778',header:'plain',heading:'rule',font:'condensed',size:10,margin:40},
 {name:'Minimal',label:'Minimal',description:'Quiet typography · generous spacing',layout:'single',accent:'#222222',header:'centered',heading:'plain',font:'sans',size:10,margin:50},
 {name:'Tech',label:'Technical',description:'Compact · accent rail',layout:'single',accent:'#315946',header:'rail',heading:'uppercase',font:'sans',size:9,margin:38},
 {name:'Executive',label:'Executive',description:'Serif name · centered masthead',layout:'single',accent:'#44394f',header:'centered',heading:'rule',font:'serif',size:10,margin:48},
 {name:'Studio',label:'Signature Banner',description:'Color masthead · clean sections',layout:'single',accent:'#8b3d32',header:'banner',heading:'uppercase',font:'sans',size:9.5,margin:42},
 {name:'Editorial',label:'Editorial',description:'Right-hand skills rail · serif',layout:'sidebar-right',accent:'#564f39',header:'plain',heading:'plain',font:'editorial',size:10,margin:40},
 {name:'Compact',label:'Compact',description:'Dense experience · restrained headings',layout:'single',accent:'#243c64',header:'plain',heading:'uppercase',font:'sans',size:8.5,margin:32}
];
const pick=(v,list,fallback)=>list.includes(v)?v:fallback;
export function designFor(template,custom){const base=TEMPLATES.find(t=>t.name===template)||TEMPLATES[0];if(!custom||typeof custom!=='object')return {...base,paper:'A4'};return {...base,paper:'A4',layout:pick(custom.layout,['single','sidebar-left','sidebar-right'],base.layout),accent:/^#[0-9a-f]{6}$/i.test(custom.accent||'')?custom.accent:base.accent,header:pick(custom.header,['plain','centered','banner','rail'],base.header),heading:pick(custom.heading,['rule','plain','uppercase'],base.heading),font:pick(custom.font,FONTS.map(f=>f.id),base.font),size:Math.max(8,Math.min(12,Number(custom.size)||base.size)),margin:Math.max(28,Math.min(56,Number(custom.margin)||base.margin))};}
export function splitSections(sections){const header=sections[0]?.title==='Header'?sections[0]:null;const body=header?sections.slice(1):sections;const side=body.filter(s=>/^(contact|skills|technical skills|top skills|languages|education|certifications|certificates|kenntnisse|ausbildung|compétences|formation)$/i.test(s.title||''));return {header,main:body.filter(s=>!side.includes(s)),side};}

export function flowText(section){const text=String(section.text||'');return /^(professional summary|summary|profile|profil|about)$/i.test(section.title||'')?text.split(/\n\s*\n/).map(p=>p.replace(/\s*\n\s*/g,' ')).join('\n\n'):text;}
