import {SCRIPT_FONTS,languageFor,fontsForLanguage} from './languages.mjs';
export const FONTS=[{id:'sans',label:'DejaVu Sans',family:'Atelier Sans',file:'DejaVuSans'},{id:'serif',label:'DejaVu Serif',family:'Atelier Serif',file:'DejaVuSerif'},{id:'condensed',label:'DejaVu Sans Condensed',family:'Atelier Condensed',file:'DejaVuSansCondensed'},{id:'editorial',label:'DejaVu Serif Condensed',family:'Atelier Editorial',file:'DejaVuSerifCondensed'},{id:'mono',label:'DejaVu Sans Mono',family:'Atelier Mono',file:'DejaVuSansMono'},...SCRIPT_FONTS];
export const TEMPLATES=[
 {name:'Professional',label:'Professional',description:'Classic rules · single column',layout:'single',accent:'#234b55',header:'plain',heading:'rule',font:'sans',size:10,margin:42},
 {name:'Modern',label:'Nordic Sidebar',description:'Skills rail · two columns',layout:'sidebar-left',accent:'#344778',header:'plain',heading:'rule',font:'condensed',size:10,margin:40},
 {name:'Minimal',label:'Minimal',description:'Quiet typography · generous spacing',layout:'single',accent:'#222222',header:'centered',heading:'plain',font:'sans',size:10,margin:50},
 {name:'Tech',label:'Technical',description:'Compact · accent rail',layout:'single',accent:'#315946',header:'rail',heading:'uppercase',font:'sans',size:10,margin:38},
 {name:'Executive',label:'Executive',description:'Serif name · centered masthead',layout:'single',accent:'#44394f',header:'centered',heading:'rule',font:'serif',size:10,margin:48},
 {name:'Studio',label:'Signature Banner',description:'Color masthead · clean sections',layout:'single',accent:'#8b3d32',header:'banner',heading:'uppercase',font:'sans',size:10,margin:42},
 {name:'Editorial',label:'Editorial',description:'Right-hand skills rail · serif',layout:'sidebar-right',accent:'#564f39',header:'plain',heading:'plain',font:'editorial',size:10,margin:40},
 {name:'Harbor',label:'Harbor Portrait',description:'Navy masthead · slate skills rail',layout:'sidebar-left',accent:'#30394b',sideColor:'#e9e9e7',header:'banner',heading:'rule',font:'sans',size:10,margin:40,volume:'balanced'},
 {name:'Sage',photoPlacement:'sidebar',label:'Sage Graduate',description:'Teal sidebar · warm peach masthead',layout:'sidebar-left',accent:'#396f70',sideColor:'#396f70',headerColor:'#edcec0',header:'banner',heading:'uppercase',font:'serif',size:10.5,margin:44,volume:'short'},
 {name:'Blush',photoPlacement:'sidebar',label:'Blush Atelier',description:'Soft pink rail · editorial typography',layout:'sidebar-left',accent:'#765450',sideColor:'#f1dfe0',header:'centered',heading:'band',font:'editorial',size:10,margin:42,volume:'short'},
 {name:'Summit',photoPlacement:'sidebar',label:'Summit Executive',description:'Dark blue right rail · refined serif',layout:'sidebar-right',accent:'#23435b',sideColor:'#23435b',header:'plain',heading:'rule',font:'serif',size:10,margin:40,volume:'long'},
 {name:'Forest',photoPlacement:'sidebar',label:'Forest Founder',description:'Deep teal sidebar · clear sections',layout:'sidebar-left',accent:'#086768',sideColor:'#086768',header:'plain',heading:'rule',font:'sans',size:10,margin:40,volume:'long'},
 {name:'Timeline',label:'Green Timeline',description:'Single column · experience timeline',layout:'single',accent:'#22654f',header:'plain',heading:'timeline',font:'sans',size:10,margin:40,volume:'long'},
 {name:'Compact',label:'Compact',description:'Dense experience · restrained headings',layout:'single',accent:'#243c64',header:'plain',heading:'uppercase',font:'sans',size:10,margin:36}
];
const pick=(v,list,fallback)=>list.includes(v)?v:fallback;
const validColor=(value,fallback)=>/^#[0-9a-f]{6}$/i.test(value||'')?value:fallback;
function sectionStyles(input,fonts){if(!input||typeof input!=='object'||Array.isArray(input))return {};return Object.fromEntries(Object.entries(input).slice(0,100).filter(([id,v])=>id.length<=150&&v&&typeof v==='object').map(([id,v])=>[id,{font:pick(v.font,fonts.map(f=>f.id),fonts[0].id),size:Math.max(10,Math.min(12,Number(v.size)||10)),headingFont:pick(v.headingFont,fonts.map(f=>f.id),fonts[0].id),headingSize:Math.max(11,Math.min(18,Number(v.headingSize)||12)),headingColor:validColor(v.headingColor,'#234b55'),bannerColor:validColor(v.bannerColor,'#f0f3f6')} ]));}

export function designFor(template,custom){const base=TEMPLATES.find(t=>t.name===template)||TEMPLATES[0];if(!custom||typeof custom!=='object')custom={};const language=languageFor(custom.language),fonts=fontsForLanguage(FONTS,language.id),layout=language.dir==='rtl'?(base.layout==='sidebar-left'?'sidebar-right':base.layout==='sidebar-right'?'sidebar-left':base.layout):base.layout;return {...base,paper:'A4',language:language.id,direction:language.dir||'ltr',layout:pick(custom.layout,['single','sidebar-left','sidebar-right'],layout),accent:/^#[0-9a-f]{6}$/i.test(custom.accent||'')?custom.accent:base.accent,header:pick(custom.header,['plain','centered','banner','rail'],base.header),heading:pick(custom.heading,['rule','plain','uppercase','band','timeline'],base.heading),font:pick(custom.font,fonts.map(f=>f.id),fonts.some(f=>f.id===base.font)?base.font:fonts[0].id),photoPlacement:pick(custom.photoPlacement,['header','sidebar'],base.photoPlacement||'header'),sideColor:/^#[0-9a-f]{6}$/i.test(custom.sideColor||'')?custom.sideColor:(base.sideColor||'#f0f3f6'),headerColor:/^#[0-9a-f]{6}$/i.test(custom.headerColor||'')?custom.headerColor:(base.headerColor||base.accent),size:Math.max(10,Math.min(12,Number(custom.size)||base.size)),margin:Math.max(36,Math.min(56,Number(custom.margin)||base.margin)),headerAlign:pick(custom.headerAlign,['left','center','right'],base.header==='centered'?'center':language.dir==='rtl'?'right':'left'),headerFont:pick(custom.headerFont,fonts.map(f=>f.id),pick(custom.font,fonts.map(f=>f.id),fonts[0].id)),headingFont:pick(custom.headingFont,fonts.map(f=>f.id),pick(custom.font,fonts.map(f=>f.id),fonts[0].id)),sideFont:pick(custom.sideFont,fonts.map(f=>f.id),pick(custom.font,fonts.map(f=>f.id),fonts[0].id)),headerSize:Math.max(18,Math.min(36,Number(custom.headerSize)||27)),headingSize:Math.max(11,Math.min(18,Number(custom.headingSize)||12)),sideSize:Math.max(10,Math.min(12,Number(custom.sideSize)||Number(custom.size)||base.size)),headingColor:validColor(custom.headingColor,validColor(custom.accent,base.accent)),sectionStyles:sectionStyles(custom.sectionStyles,fonts)};}
export function headerLines(text){const lines=String(text||'').split('\n');if(lines[0]?.split(/\s+/).length>8){const first=lines[0],role=first.match(/\b(?:Fulfilment|Fulfillment|Independent|Senior|Junior|Operations|Software|Data|Marketing|Business|Project|Product|Financial|Sales|Customer|Warehouse|Logistics)\b/i);if(role&&role.index>0&&first.slice(0,role.index).trim().split(/\s+/).length<=5)lines.splice(0,1,first.slice(0,role.index).trim(),first.slice(role.index).trim());}return lines.flatMap(line=>line.replace(/(?:https?:\/\/|www\.)[^\s]+|[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}|\+\d[\d\s-]{5,}/g,match=>'\n'+match).split('\n')).map(x=>x.trim()).filter(Boolean);}
export function splitSections(sections){const header=sections[0]?.title==='Header'?{...sections[0],text:headerLines(sections[0].text).join('\n')}:null;const body=header?sections.slice(1):sections;const side=body.filter(s=>/^(contact|core skills|skills|technical skills|top skills|languages|education|certifications|certificates|kenntnisse|ausbildung|compétences|formation)$/i.test(s.title||''));return {header,main:body.filter(s=>!side.includes(s)),side};}

export function flowText(section){const text=String(section.text||'');if(section.inlineStyles?.text?.length)return text;return /^(professional summary|summary|profile|profil|about)$/i.test(section.title||'')?text.split(/\n\s*\n/).map(p=>p.replace(/\s*\n\s*/g,' ')).join('\n\n'):text;}

export function templateFits(template,volume){return volume!=='long'||!['short'].includes(template.volume)||false;}
export function photoData(value){return typeof value==='string'&&value.length<900000&&/^data:image\/(?:png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(value)?value:null;}

export function colorInk(color){const c=/^#[0-9a-f]{6}$/i.test(color||'')?color:'#ffffff';const v=c.slice(1).match(/../g).map(x=>parseInt(x,16));return v[0]*.299+v[1]*.587+v[2]*.114<145?'#ffffff':'#273439';}
