import {PDFDocument,rgb,PDFName,PDFString,pushGraphicsState,popGraphicsState,moveTo,appendBezierCurve,closePath,clip,endPath} from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import {FONTS,designFor,splitSections,flowText,photoData,colorInk} from './design.mjs';
import {languageFor,detectLanguage} from './languages.mjs';
import {drawShaped,shapedWidth,shapedLinkRects} from './shapedText.mjs';
import { isMetaContent, validateCV, normalizeSection } from './contentEngine.mjs';
import {inlineRuns} from './inlineStyles.mjs';
export async function renderPDF(doc,loadFonts){
 if(!Array.isArray(doc.sections)||!doc.sections.some(s=>s.text?.trim()))throw Error('No document content to export.');
 doc={...doc,sections:doc.sections.map(normalizeSection)};

 if(doc.kind==='cv'&&doc.sections.some(s=>s.text.split('\n').some(isMetaContent)))throw Error('Remove analysis comments or page artifacts from the CV before exporting. Your draft is unchanged.');
 if(doc.cvGenerationVersion===2&&!doc.measure){const qc=validateCV(doc.sections);if(!qc.valid)throw Error(qc.issues.join('. '));}
 const language=languageFor(doc.language||doc.design?.language||detectLanguage(doc.sections.map(s=>s.text).join(' '))),d=designFor(doc.template,{...doc.design,language:language.id}),document=await PDFDocument.create();document.registerFontkit(fontkit);const data=await loadFonts(d.font);
 const embedded=new Map(),raws=new Map();
 const inlineFonts=doc.sections.flatMap(s=>['text','title'].flatMap(field=>inlineRuns(s,field).map(r=>r.font))).filter(id=>FONTS.some(f=>f.id===id));
 for(const id of new Set([d.font,d.headerFont,d.headingFont,d.sideFont,...inlineFonts,...Object.values(d.sectionStyles||{}).flatMap(s=>[s.font,s.headingFont])])){const bytes=id===d.font?data:await loadFonts(id);const pair=await Promise.all(bytes.map(bytes=>document.embedFont(bytes,{subset:true})));embedded.set(id,pair);pair.forEach((f,i)=>raws.set(f,fontkit.create(bytes[i])));}
 const [normal,bold]=embedded.get(d.font),[headerNormal,headerBold]=embedded.get(d.headerFont),[,headingBold]=embedded.get(d.headingFont),[sideNormal,sideBold]=embedded.get(d.sideFont),complex=language.script==='arabic'||language.script==='devanagari';
 const textWidth=(text,font,size)=>complex?shapedWidth(text,raws.get(font),size,d.direction):font.widthOfTextAtSize(text,size);
 if(complex){const raw=raws.get(normal);for(const c of doc.sections.map(s=>s.text+' '+(s.displayTitle||s.title)).join(' ')){if(!/[\s\u200c\u200d•●▪]/.test(c)&&!raw.hasGlyphForCodePoint(c.codePointAt(0)))throw Error('The selected font cannot display a character in this CV. Choose another font or correct the text.');}}
 document.setTitle(doc.title||'Career document');const width=595.276,height=841.89,margin=d.margin,bottom=40,accent=rgb(...d.accent.slice(1).match(/../g).map(x=>parseInt(x,16)/255)),ink=rgb(.12,.16,.18),white=rgb(1,1,1);
 const sideColor=rgb(...(d.sideColor||'#f0f3f6').slice(1).match(/../g).map(x=>parseInt(x,16)/255)),sideDark=colorInk(d.sideColor)==='#ffffff';
 const columns=doc.kind==='cv'&&d.layout!=='single'&&splitSections(doc.sections).side.length>0,sideWidth=columns?132:0,gap=24,mainWidth=width-2*margin-sideWidth-(columns?gap:0),sideX=d.layout==='sidebar-right'?width-margin-sideWidth:margin,mainX=columns&&d.layout==='sidebar-left'?margin+sideWidth+gap:margin;
 const pages=[],tops=[];
 function pageAt(index){while(pages.length<=index){const p=document.addPage([width,height]);if(columns&&pages.length>0)p.drawRectangle({x:sideX-10,y:bottom-8,width:sideWidth+20,height:height-margin-bottom+8,color:sideColor});if(d.header==='rail')p.drawRectangle({x:d.direction==='rtl'?width-margin+12:margin-15,y:bottom,width:3,height:height-margin-bottom,color:accent});p.drawText(String(pages.length+1),{x:width-margin-12,y:23,size:8,font:normal,color:rgb(.4,.45,.46)});pages.push(p);tops.push(height-margin);}return pages[index];}pageAt(0);
 function wrap(text,font,size,w){const result=[];for(const original of String(text).split('\n')){if(!original.trim()){result.push('');continue;}let line='';for(const word of original.trim().split(/\s+/)){if(textWidth(word,font,size)>w){if(line){result.push(line);line='';}let part='';for(const char of word){if(textWidth(part+char,font,size)>w){result.push(part);part='';}part+=char;}line=part;continue;}if(line&&textWidth(line+' '+word,font,size)>w){result.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)result.push(line);}
 // Rebalance a final single word without breaking the source sentence.
 if(result.length>1&&result.at(-1).trim().split(/\s+/).length===1){const prior=result.at(-2).split(' ');if(prior.length>2){const last=prior.pop(),joined=last+' '+result.at(-1);if(textWidth(joined,font,size)<=w){result[result.length-2]=prior.join(' ');result[result.length-1]=joined;}}}
 return result;}
 function write(flow,text,{font=normal,size=d.size,leading=d.size*1.48,color=ink,after=5,align='start'}={}){
  const links=[];
  const readable=String(text).replace(/https:\/\/[^\s<>]+/g,uri=>{let display=uri.replace(/^https:\/\/(?:www\.)?/,'').replace(/\?.*$/,'').replace(/\/$/,'');if(textWidth(display,font,size)>flow.w)display=display.split('/')[0]+' / link';links.push({display,uri});return display;});
  for(const line of wrap(readable,font,size,flow.w)){
   if(!line.trim()){flow.y-=leading*.28;continue;}if(flow.y-leading<bottom){flow.i++;pageAt(flow.i);flow.y=tops[flow.i];}
   const p=pageAt(flow.i),x=flow.x+(align==='center'?(flow.w-textWidth(line,font,size))/2:align==='right'||align==='start'&&d.direction==='rtl'?flow.w-textWidth(line,font,size):0);
   if(complex)drawShaped(p,line,{x,y:flow.y-size,size,font,raw:raws.get(font),color,direction:d.direction});else p.drawText(line,{x,y:flow.y-size,size,font,color});
   const visibleLinks=[...links.filter(l=>line.includes(l.display)).map(l=>({...l,index:line.indexOf(l.display)})),...[...line.matchAll(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g)].map(m=>({display:m[0],uri:'mailto:'+m[0],index:m.index}))];
   for(const l of visibleLinks){const rects=complex?shapedLinkRects(line,raws.get(font),size,d.direction,l.index,l.index+l.display.length):[{x:textWidth(line.slice(0,l.index),font,size),width:textWidth(l.display,font,size)}];for(const rect of rects){const linkX=x+rect.x,w=rect.width,annotation=document.context.register(document.context.obj({Type:'Annot',Subtype:'Link',Rect:[linkX,flow.y-size-2,linkX+w,flow.y+1],Border:[0,0,0],A:{Type:'Action',S:'URI',URI:PDFString.of(l.uri)}}));let annots=p.node.lookup(PDFName.of('Annots'));if(!annots){annots=document.context.obj([]);p.node.set(PDFName.of('Annots'),annots);}annots.push(annotation);}}
   flow.y-=leading;
  }flow.y-=after;
 }
 function writeRich(flow,section,field,start,end,opts){
  let row=[],usedWidth=0;
  const flush=()=>{if(!row.length)return;const leading=Math.max(...row.map(r=>r.size))*1.4;if(flow.y-leading<bottom){flow.i++;pageAt(flow.i);flow.y=tops[flow.i];}
   let x=flow.x+(opts.align==='center'?(flow.w-usedWidth)/2:opts.align==='right'||!opts.align&&d.direction==='rtl'?flow.w-usedWidth:0);const order=d.direction==='rtl'?[...row].reverse():row;
   if(!opts.measure)for(const r of order){const temp={...flow,x,w:Math.max(r.width+.1,1)};write(temp,r.text,{font:r.font,size:r.size,color:r.color,leading,after:0,align:'left'});x+=r.width;}flow.y-=leading;row=[];usedWidth=0;
  };
  for(const r of inlineRuns(section,field,start,end)){const pair=embedded.get(r.font),defaultBold=[...embedded.values()].some(pair=>pair[1]===opts.font),font=pair?pair[(r.bold??defaultBold)?1:0]:opts.font,size=r.size||opts.size||d.size,color=r.color?rgb(...r.color.slice(1).match(/../g).map(x=>parseInt(x,16)/255)):opts.color||ink;
   for(const text of r.text.match(/\n|[^\S\n]+|\S+/g)||[]){if(text==='\n'){flush();continue;}const width=textWidth(text,font,size);if(width>flow.w){flush();for(const piece of wrap(text,font,size,flow.w)){row.push({text:piece,font,size,color,width:textWidth(piece,font,size)});flush();}continue;}if(usedWidth+width>flow.w&&row.length)flush();if(!row.length&&!text.trim())continue;row.push({text,font,size,color,width});usedWidth+=width;}
  }flush();flow.y-=opts.after??2;
 }
 const group=splitSections(doc.sections),header=doc.kind==='cv'?group.header:null,bodyTop=height-margin;
 let portrait=null;if(doc.kind==='cv'&&photoData(doc.portrait)){const data=Uint8Array.from(atob(doc.portrait.split(',')[1]),c=>c.charCodeAt(0));portrait=doc.portrait.startsWith('data:image/png')?await document.embedPng(data):await document.embedJpg(data);}
 const sidePortrait=portrait&&columns&&d.photoPlacement==='sidebar';
 const mast={i:0,x:margin+(d.direction==='rtl'&&portrait&&!sidePortrait?80:0),y:bodyTop,w:width-margin*2-(portrait&&!sidePortrait?80:0)};
 if(header){const [name,...rest]=header.text.split('\n');const nameSize=Math.max(d.headerSize,...inlineRuns(header,'text',0,name.length).map(r=>r.size||0)),contactSize=Math.max(d.size,...inlineRuns(header,'text',name.length+1).map(r=>r.size||0));let headerHeight=wrap(name,headerBold,nameSize,mast.w).length*nameSize*1.4+wrap(rest.join('\n'),headerNormal,contactSize,mast.w).length*contactSize*1.48+35;if(header.inlineStyles?.text?.length){const probe={...mast};writeRich(probe,header,'text',0,name.length,{font:headerBold,size:d.headerSize,after:9,measure:true});writeRich(probe,header,'text',name.length+1,undefined,{font:headerNormal,size:d.size,after:20,measure:true});headerHeight=Math.max(headerHeight,bodyTop-probe.y+12);}if(headerHeight>height/2)throw Error('Header is too long. Move experience and skills into separate sections before exporting.');if(d.header==='banner'){const nameLines=wrap(name,headerBold,d.headerSize,mast.w),contactLines=wrap(rest.join('\n'),headerNormal,d.size,mast.w),block=headerHeight;if(block>height/2)throw Error('Header is too long for a banner. Choose another layout or move details to a section.');pages[0].drawRectangle({x:margin-12,y:mast.y-block,width:width-margin*2+24,height:block+12,color:rgb(...(d.headerColor||d.accent).slice(1).match(/../g).map(x=>parseInt(x,16)/255))});}if(header.inlineStyles?.text?.length)writeRich(mast,header,'text',0,name.length,{align:d.headerAlign,font:headerBold,size:d.headerSize,color:d.header==='banner'?(colorInk(d.headerColor||d.accent)==='#ffffff'?white:ink):accent,after:9});else write(mast,name,{font:headerBold,size:d.headerSize,leading:d.headerSize*1.22,color:d.header==='banner'?(colorInk(d.headerColor||d.accent)==='#ffffff'?white:ink):accent,align:d.headerAlign,after:9});if(header.inlineStyles?.text?.length)writeRich(mast,header,'text',name.length+1,undefined,{align:d.headerAlign,font:headerNormal,size:d.size,color:d.header==='banner'?(colorInk(d.headerColor||d.accent)==='#ffffff'?white:ink):ink,after:20});else write(mast,rest.join('\n'),{font:headerNormal,leading:d.size*1.4,color:d.header==='banner'?(colorInk(d.headerColor||d.accent)==='#ffffff'?white:ink):ink,align:d.headerAlign,after:20});if(d.header==='banner')mast.y=Math.min(mast.y,bodyTop-headerHeight-12);}
 function drawPortrait(x,y,size){const p=pages[0];if(d.name!=='Blush'){const r=size/2,cx=x+r,cy=y+r,k=r*.55228475;p.pushOperators(pushGraphicsState(),moveTo(cx+r,cy),appendBezierCurve(cx+r,cy+k,cx+k,cy+r,cx,cy+r),appendBezierCurve(cx-k,cy+r,cx-r,cy+k,cx-r,cy),appendBezierCurve(cx-r,cy-k,cx-k,cy-r,cx,cy-r),appendBezierCurve(cx+k,cy-r,cx+r,cy-k,cx+r,cy),closePath(),clip(),endPath());p.drawImage(portrait,{x,y,width:size,height:size});p.pushOperators(popGraphicsState());}else p.drawImage(portrait,{x,y,width:size,height:size});}
 if(portrait&&!sidePortrait){drawPortrait(d.direction==='rtl'?margin:width-margin-64,bodyTop-64,64);mast.y=Math.min(mast.y,bodyTop-84);}
 // The masthead has its own full-width region. Both columns start below it,
 // including the first section's heading ascent and band decoration.
 const startY=mast.y-12;
 if(columns)pages[0].drawRectangle({x:sideX-10,y:bottom-8,width:sideWidth+20,height:Math.max(0,startY-bottom+8),color:sideColor});
 if(sidePortrait)drawPortrait(sideX+32,startY-64,64);
 function sections(list,x,w,isSide=false,existingFlow=null){const sectionNormal=isSide?sideNormal:normal,sectionBold=isSide?sideBold:bold,sectionSize=isSide?d.sideSize:d.size;const f=existingFlow||{i:0,x,y:startY-(isSide&&sidePortrait?84:0),w};if(doc.kind!=='cv')write(f,doc.title||'Letter',{font:bold,size:12,color:accent,after:15});for(const s of list){const st=d.sectionStyles?.[s.id];const [localNormal,localBold]=st?embedded.get(st.font):[sectionNormal,sectionBold],localHeading=st?embedded.get(st.headingFont)[1]:headingBold,localSize=st?.size||sectionSize,localHeadingSize=st?.headingSize||d.headingSize,localColor=st?.headingColor||d.headingColor;if(!s.text?.trim())continue;if(s.title&&s.title!=='Header'){if(f.y-55<bottom){f.i++;pageAt(f.i);f.y=tops[f.i];}f.y-=8;if(d.heading==='band')pageAt(f.i).drawRectangle({x:x-3,y:f.y-localHeadingSize*1.4-2,width:w+6,height:localHeadingSize*1.4+5,color:rgb(...(st?.bannerColor||d.sideColor).slice(1).match(/../g).map(x=>parseInt(x,16)/255))});if(s.inlineStyles?.title?.length)writeRich(f,s,'title',0,undefined,{font:localHeading,size:localHeadingSize,color:rgb(...localColor.slice(1).match(/../g).map(x=>parseInt(x,16)/255)),after:4});else write(f,d.heading==='uppercase'?(s.displayTitle||s.title).toUpperCase():(s.displayTitle||s.title),{font:localHeading,size:localHeadingSize,leading:localHeadingSize*1.4,color:isSide&&sideDark&&!st?white:rgb(...localColor.slice(1).match(/../g).map(x=>parseInt(x,16)/255)),after:4});if(d.heading==='band')pageAt(f.i).drawRectangle({x,y:f.y+3,width:w,height:2,color:accent});if(d.heading==='timeline'&&!isSide)pageAt(f.i).drawCircle({x:x-7,y:f.y+10,size:2,color:accent});if(d.heading==='rule')pageAt(f.i).drawLine({start:{x,y:f.y+3},end:{x:x+w,y:f.y+3},thickness:.5,color:accent});}const bodyLines=flowText(s).split('\n');for(let lineIndex=0;lineIndex<bodyLines.length;lineIndex++){const line=bodyLines[lineIndex];const next=bodyLines[lineIndex+1]||'';const isRecordTitle=s.headingLines?.includes(line)||['Experience','Education','Certifications','Additional Experience'].includes(s.title)&&line&&!/^[•*-]/.test(line)&&line.length<150&&(/\b(?:19|20)\d{2}\b/.test(next)||lineIndex===0);const bodyFont=isRecordTitle?localBold:!/^[•*-]/.test(line)&&/\s[—|–]\s|\s·\s/.test(line)&&line.length<150?localBold:localNormal;const lineHeight=wrap(line,bodyFont,localSize,w).length*localSize*1.4;const keepHeight=lineHeight+(isRecordTitle?wrap(next,localNormal,localSize,w).length*localSize*1.4+localSize*1.4:0);if(keepHeight<height-margin-bottom-30&&f.y-keepHeight<bottom){f.i++;pageAt(f.i);f.y=tops[f.i];}if(s.inlineStyles?.text?.length){const offset=bodyLines.slice(0,lineIndex).join('\n').length+(lineIndex?1:0);writeRich(f,s,'text',offset,offset+line.length,{font:bodyFont,size:localSize,color:isSide&&sideDark?white:ink,after:line?2:1});}else write(f,line,{font:bodyFont,size:localSize,color:isSide&&sideDark?white:ink,leading:localSize*1.4,after:line?2:1});}f.y-=4;} }
 if(columns){const mainFlow={i:0,x:mainX,y:startY,w:mainWidth},sideFlow={i:0,x:sideX,y:startY-(sidePortrait?84:0),w:sideWidth};for(const s of doc.sections.filter(s=>s.title!=='Header')){const side=group.side.includes(s);sections([s],side?sideX:mainX,side?sideWidth:mainWidth,side,side?sideFlow:mainFlow);}}else sections(header?doc.sections.slice(1):doc.sections,margin,width-2*margin);
 if(doc.measure)return {pages:pages.length};
 if(doc.kind==='cv'&&doc.cvGenerationVersion===2&&pages.length>(doc.maxPages||2))throw Error(`This CV is ${pages.length} pages. Optimise for the current template or explicitly allow an extended CV before exporting. Your content has not been removed.`);
 return new Blob([await document.save()],{type:'application/pdf'});
}
