import {createHash} from 'node:crypto';
import https from 'node:https';import dns from 'node:dns/promises';import net from 'node:net';
import { CATEGORIES, LEVEL_POINTS, recruiterAssessment } from './recruiter.mjs';
export class ServiceError extends Error{constructor(message,status=400){super(message);this.status=status}}
export function sourceMap(cv,linkedin=''){const out={};for(const [p,text] of [['CV',cv],['LI',linkedin]])text.split('\n').forEach((line,i)=>{if(line.trim())out[p+(i+1)]=line.trim()});return out}
const refs=(ids,source)=>Array.isArray(ids)?[...new Set(ids.filter(id=>typeof id==='string'&&Object.hasOwn(source,id)))]:[];
const numbers=s=>new Set(s.match(/\b\d+(?:[.,]\d+)?%?\b/g)||[]);
export function validate(action,result,context,sources){
 if(!result||typeof result!=='object'||Array.isArray(result))throw new ServiceError('AI returned an invalid object.');
 if(action==='analysis'){
  if(!Array.isArray(result.matrix)||!result.matrix.length||result.matrix.length>100||!result.job||typeof result.job!=='object')throw new ServiceError('AI returned an invalid analysis.');
  for(const r of result.matrix){if(!r||!r.requirement||!CATEGORIES.includes(r.category)||!Object.hasOwn(LEVEL_POINTS,r.level)||!['Mandatory','Preferred','Nice to Have'].includes(r.priority))throw new ServiceError('AI returned an invalid requirement row.');r.evidenceIds=refs(r.evidenceIds,sources);r.evidence=r.evidenceIds.map(id=>sources[id]);if(['Strong Match','Partial Match','Transferable Skill'].includes(r.level)&&!r.evidenceIds.length){r.level='Unknown';r.explanation='No valid candidate evidence. Needs user confirmation.'}}
  const seen=new Set();result.matrix=result.matrix.filter(r=>{const key=String(r.requirement).toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');if(seen.has(key))return false;seen.add(key);return true;});
  const normalized=t=>String(t).replace(/\s+/g,' ').trim().toLowerCase();
  for(const r of result.matrix){
   const quote=typeof r.vacancyQuote==='string'?r.vacancyQuote.trim():'';
   r.vacancyQuote=quote&&normalized(context.vacancy||'').includes(normalized(quote))?quote:'';
   if(!r.vacancyQuote)throw new ServiceError('A requirement could not be traced to the vacancy. Retry with the complete job advert.');
   r.screeningGate=r.screeningGate===true&&r.priority==='Mandatory'&&['eligibility','languages','education','seniority'].includes(r.category);
  }
  const review=recruiterAssessment(result.matrix);result.recruiter=review;result.score=review.score;result.categories=review.categories;result.scoreNote=review.scoreNote;
  if(!Array.isArray(result.gaps))result.gaps=[];for(const r of result.matrix)if(r.priority==='Mandatory'&&['Missing','Unknown'].includes(r.level)&&!result.gaps.some(g=>g.requirement===r.requirement&&g.type==='Critical Gap'))result.gaps.push({requirement:r.requirement,type:'Critical Gap',why:'Mandatory requirement lacks confirmed evidence.',questions:[]});
 }else if(action==='changes'){
  if(!Array.isArray(result.changes))throw new ServiceError('Invalid proposal list.');const valid=[],blocked=[];
  for(const c of result.changes){const section=context.cv?.find(s=>s.id===c.sectionId);if(!section||typeof c.original!=='string'||!c.original||!section.text.includes(c.original)||typeof c.proposed!=='string'||!c.proposed.trim()){blocked.push('A stale or invalid proposal was blocked.');continue}if(context.selectedSection&&c.sectionId!==context.selectedSection)continue;const ids=refs(c.evidenceIds,sources);if(!ids.length){blocked.push('A proposal lacked candidate evidence.');continue}const evidence=ids.map(id=>sources[id]),supported=evidence.join(' '),known=numbers(c.original+' '+supported);const newNumbers=[...numbers(c.proposed)].filter(n=>!known.has(n));const risky=['SAP PP','MES','ERP','production order management','manufacturing production planning'].filter(term=>new RegExp('\\b'+term+'\\b','i').test(c.proposed)&&!new RegExp('\\b'+term+'\\b','i').test(supported));const officialLine=section.text.split('\n').some((line,i)=>line.trim()===c.original.trim()&&(/—|\s-\s|\s@\s/.test(line)||(i===0&&/experience|employment|berufserfahrung|expérience/i.test(section.title))));if(newNumbers.length||risky.length||(officialLine&&!c.proposed.includes(c.original))){blocked.push('Unsupported specialist claim, metric or official title change blocked.');continue}const id=createHash('sha256').update(c.sectionId+'\0'+c.original+'\0'+c.proposed).digest('hex');if(context.rejected?.includes(id))continue;valid.push({...c,id,evidenceIds:ids,evidence,safe:c.original===c.proposed,needsConfirmation:c.original!==c.proposed,status:'pending'})}
  result.changes=valid;result.blocked=blocked;
 }else if(action==='cover'||action==='motivation'){
  if(!Array.isArray(result.paragraphs)||result.paragraphs.some(p=>!p||typeof p.text!=='string'))throw new ServiceError('Invalid letter response.');result.paragraphs=result.paragraphs.map(p=>({...p,evidenceIds:refs(p.evidenceIds,sources),evidence:refs(p.evidenceIds,sources).map(id=>sources[id]),needsConfirmation:true}));result.reviewRequired=true;
 }else if(action==='interview'&&!Array.isArray(result.questions))throw new ServiceError('Invalid interview response.');return result;
}
function publicIP(ip){if(net.isIP(ip)===4){const a=ip.split('.').map(Number);return !(a[0]===0||a[0]===10||a[0]===127||a[0]>=224||(a[0]===169&&a[1]===254)||(a[0]===172&&a[1]>=16&&a[1]<=31)||(a[0]===192&&(a[1]===168||a[1]===0))||(a[0]===100&&a[1]>=64&&a[1]<=127)||(a[0]===198&&(a[1]===18||a[1]===19||a[1]===51))||(a[0]===203&&a[1]===0))}return false;}
export async function fetchPublic(url,lookup=dns.lookup){for(let n=0;n<5;n++){let target;try{target=new URL(url)}catch{throw new ServiceError('Enter a valid public HTTPS URL.')}if(target.protocol!=='https:'||target.username||target.password||(target.port&&target.port!=='443')||/(^|\.)linkedin\.com$/i.test(target.hostname))throw new ServiceError('Use a public HTTPS URL. LinkedIn pages cannot be fetched; paste profile text or upload your export.');const addresses=await lookup(target.hostname,{all:true,family:4});if(!addresses.length||addresses.some(x=>!publicIP(x.address)))throw new ServiceError('Private, reserved and local addresses are blocked.');const ip=addresses[0].address;const response=await new Promise((resolve,reject)=>{const req=https.get(target,{headers:{'User-Agent':'CareerAtelier/2.0',Accept:'text/html,text/plain'},lookup:(host,options,cb)=>{if(options?.all)cb(null,[{address:ip,family:4}]);else cb(null,ip,4)},timeout:20000},res=>{if([301,302,303,307,308].includes(res.statusCode)){res.resume();resolve({redirect:res.headers.location});return}if(res.statusCode!==200){res.resume();reject(new ServiceError('Public page unavailable. Paste its text instead.'));return}let bytes=0,chunks=[];res.on('data',b=>{bytes+=b.length;if(bytes>2*1024*1024){req.destroy();reject(new ServiceError('Public page exceeds 2 MB.'))}else chunks.push(b)});res.on('end',()=>resolve({type:res.headers['content-type'],data:Buffer.concat(chunks).toString('utf8')}));res.on('error',reject)});req.on('timeout',()=>req.destroy(new ServiceError('Public page timed out.')));req.on('error',reject)});if(response.redirect){url=new URL(response.redirect,target).href;continue}if(!/text\/(html|plain)/i.test(response.type||''))throw new ServiceError('Upload this document or paste its text.');let text=response.data;if(/html/i.test(response.type))text=text.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>|<style\b[^>]*>[\s\S]*?<\/style\s*>/gi,'').replace(/<\/?(?:p|div|br|li|h[1-6]|section|tr)\b[^>]*>/gi,'\n').replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"');text=text.split('\n').map(s=>s.replace(/\s+/g,' ').trim()).filter(Boolean).join('\n');if(text.length<80)throw new ServiceError('Page contains too little readable text. Paste the vacancy.');return{text:text.slice(0,100000),url:target.href,retrievedAt:new Date().toISOString()}}throw new ServiceError('Too many redirects.');}
export async function limitedText(request){const limit=2*1024*1024;if(Number(request.headers.get('content-length'))>limit)throw new ServiceError('Request too large.',413);if(!request.body)return '';const reader=request.body.getReader(),decoder=new TextDecoder();let text='',bytes=0;try{for(;;){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>limit){await reader.cancel();throw new ServiceError('Request too large.',413)}text+=decoder.decode(value,{stream:true})}return text+decoder.decode()}finally{reader.releaseLock()}}
