"use server";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/admin/adminAuth";
import { getCareerBySlug } from "@/lib/admin/careerRepository";
import { currentPublishedFor,getAdminSnapshot,publishCandidate,rejectCandidate } from "@/lib/admin/adminIntelligenceRepository";
import { queueAdminRefresh } from "@/lib/intelligence/adminRefreshQueue";
import{validateAdminRefresh}from"@/lib/intelligence/adminRefreshValidation";
import { resolveCareer,type SnapshotType } from "@/lib/intelligence/snapshotRegistry";
import type { RefreshCareerDefinition } from "@/lib/intelligence/refreshEngine";
import { salaryQuality,salaryReviewMetrics } from "@/lib/intelligence/salaryCandidateReview";
export interface IntelligenceActionState{error?:string}
async function admin(){const auth=await requireAdmin();if(auth.status!=="admin")throw new Error("ADMIN_REQUIRED");return auth}
async function definition(token:string,slug:string):Promise<RefreshCareerDefinition|null>{const code=resolveCareer(slug);if(code)return{careerSlug:code.careerSlug,canonicalTitle:code.canonicalTitle,directTitles:[...code.directTitles],equivalentTitles:[...code.equivalentTitles],adjacentTitles:[...code.adjacentTitles],version:String(code.version)};const career=await getCareerBySlug(token,slug);if(!career)return null;return{careerSlug:career.slug,canonicalTitle:career.taxonomy.primaryTitle,directTitles:[career.taxonomy.primaryTitle],equivalentTitles:career.taxonomy.aliases,adjacentTitles:[],version:`db-${new Date(career.updated_at).getTime()}`}}
export async function queueRefreshAction(_state:IntelligenceActionState,formData:FormData):Promise<IntelligenceActionState>{const auth=await admin(),careerSlug=String(formData.get("career")??""),countries=formData.getAll("countries").map(String),types=formData.getAll("types").map(String),provider=String(formData.get("provider")??""),sampleSize=Number(formData.get("sampleSize")),careerDefinition=await definition(auth.accessToken,careerSlug),check=validateAdminRefresh({careerSlug,countries,types,provider,sampleSize,definition:careerDefinition});if(!check.valid)return{error:check.errors.join(" · ")};let run;try{run=await queueAdminRefresh({definition:careerDefinition!,countries,types:types as SnapshotType[],sampleSize,actorUserId:auth.user.id})}catch(error){const code=error instanceof Error?error.message:"REFRESH_FAILED";if(code==="DUPLICATE_ACTIVE_REFRESH")return{error:"An overlapping refresh item is still queued, processing, or scheduled for retry."};if(code==="CANDIDATE_AWAITING_REVIEW")return{error:"A candidate for this Career, country, and snapshot type is awaiting review. Publish or reject it before starting another refresh."};if(code==="REQUEST_BUDGET_EXCEEDED")return{error:"This refresh exceeds the configured provider request budget."};return{error:"Refresh could not be queued."}}redirect(`/admin/intelligence/runs/${run.runId}`)}
export async function publishCandidateAction(formData:FormData){const auth=await admin(),id=String(formData.get("id")??""),candidate=await getAdminSnapshot(auth.accessToken,id);if(!candidate)redirect(`/admin/intelligence/candidates/${id}?error=Candidate+not+found`);const current=await currentPublishedFor(auth.accessToken,candidate),acknowledged=formData.get("acknowledgeHighChange")==="yes";if(candidate.snapshot_type==="salary"){const quality=salaryQuality(salaryReviewMetrics(candidate),current?salaryReviewMetrics(current):null);if(!quality.valid)redirect(`/admin/intelligence/candidates/${id}?error=Salary+candidate+failed+structural+validation`);if(quality.requiresAcknowledgement&&!acknowledged)redirect(`/admin/intelligence/candidates/${id}?error=High-change+acknowledgement+is+required`)}await publishCandidate(auth.accessToken,id,acknowledged);redirect(`/admin/intelligence/candidates/${id}?reviewed=published`)}
export async function rejectCandidateAction(formData:FormData){const auth=await admin(),id=String(formData.get("id")??""),reason=String(formData.get("reason")??"");await rejectCandidate(auth.accessToken,id,reason);redirect(`/admin/intelligence/candidates/${id}?reviewed=rejected`)}
