import assert from"node:assert/strict";import fs from"node:fs";import{accessTokenNeedsRefresh,ADMIN_ACCESS_COOKIE,ADMIN_REFRESH_COOKIE}from"../src/lib/admin/adminSession.ts";import{collectAdzunaPages}from"../src/lib/intelligence/adzunaPagination.ts";import{validateAdminRefresh}from"../src/lib/intelligence/adminRefreshValidation.ts";
const token=(exp:number)=>`x.${btoa(JSON.stringify({exp})).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_")}.x`,now=2_000_000_000;assert.equal(accessTokenNeedsRefresh(token(now+1000),now),false);assert.equal(accessTokenNeedsRefresh(token(now+100),now),true);assert.equal(accessTokenNeedsRefresh("invalid",now),true);
const pages=await collectAdzunaPages({maxResults:5,pageSize:2,loadPage:async page=>({count:20,results:page===1?[{id:"1"},{id:"2"}]:page===2?[{id:"2"},{id:"3"}]:[]})});assert.equal(pages.providerReportedCount,20);assert.equal(pages.pagesRequested,3);assert.deepEqual(pages.results.map(x=>x.id),["1","2","3"]);assert.equal(pages.partial,false);
const last=await collectAdzunaPages({maxResults:10,pageSize:5,loadPage:async()=>({count:2,results:[{id:"1"},{id:"2"}]})});assert.equal(last.pagesRequested,1);
await assert.rejects(()=>collectAdzunaPages({maxResults:10,pageSize:5,loadPage:async()=>{throw Object.assign(new Error("rate"),{providerStatus:"rate-limited"})}}));
let attempts=0;const partial=await collectAdzunaPages({maxResults:4,pageSize:2,loadPage:async page=>{if(page===1)return{count:10,results:[{id:"1"},{id:"2"}]};attempts++;throw Object.assign(new Error("timeout"),{providerStatus:"provider-error"})}});assert.equal(partial.partial,true);assert.equal(attempts,3);assert.equal(partial.recordsRetrieved,2);
const definition={careerSlug:"ai-engineer",canonicalTitle:"AI Engineer",directTitles:["AI Engineer"],equivalentTitles:[],adjacentTitles:[],version:"1"};assert.equal(validateAdminRefresh({careerSlug:"ai-engineer",countries:["gb"],types:["market"],provider:"adzuna",sampleSize:100,definition}).valid,true);assert.ok(validateAdminRefresh({careerSlug:"x",countries:["es"],types:["bad"],provider:"other",sampleSize:500,definition:null}).errors.length>=4);
const proxy=fs.readFileSync("src/proxy.ts","utf8"),actions=fs.readFileSync("src/app/admin/(studio)/intelligence/actions.ts","utf8"),route=fs.readFileSync("src/app/api/admin/intelligence/runs/[runId]/process/route.ts","utf8"),repository=fs.readFileSync("src/lib/intelligence/snapshotRepository.ts","utf8"),migration=fs.readFileSync("supabase/migrations/202607170002_admin_intelligence_studio.sql","utf8"),login=fs.readFileSync("src/app/admin/login/actions.ts","utf8");assert.match(proxy,/grant_type=refresh_token/);assert.match(proxy,/cookies\.set\(ADMIN_REFRESH_COOKIE/);assert.match(login,new RegExp(`delete\\(${ADMIN_ACCESS_COOKIE.includes("access")?"ADMIN_ACCESS_COOKIE":"x"}\\)`));assert.match(login,/delete\(ADMIN_REFRESH_COOKIE\)/);assert.match(actions,/requireAdmin/);assert.match(route,/requireAdmin/);assert.match(repository,/saveCandidate/);assert.match(repository,/status:"validating"/);assert.match(repository,/status=eq\.published/);assert.doesNotMatch(actions,/CRON_SECRET|ADZUNA_APP_KEY|SUPABASE_SECRET_KEY/);assert.match(migration,/admin_publish_intelligence_candidate/);assert.match(migration,/admin_reject_intelligence_candidate/);assert.match(migration,/claim_next_intelligence_refresh_item/);assert.match(migration,/status='superseded'/);assert.match(migration,/status='published'/);assert.match(migration,/status='rejected'/);assert.match(migration,/intelligence_review_audit/);
console.log("Admin Intelligence authorization, session rotation, refresh validation, pagination, candidate review, and publication checks passed.");
