"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { CAREER_CATALOG } from "@/data/careerCatalog";

export default function CareerSearch() {
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const inputRef = useRef<HTMLInputElement>(null); const router = useRouter();
  const results = useMemo(() => query.trim() ? CAREER_CATALOG.filter((career) => `${career.title} ${career.domain}`.toLowerCase().includes(query.toLowerCase())).slice(0, 6) : [], [query]);
  useEffect(() => { const focus = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); inputRef.current?.focus(); setOpen(true); } }; window.addEventListener("keydown", focus); return () => window.removeEventListener("keydown", focus); }, []);
  function choose(route?: string) { if (route) { setOpen(false); setQuery(""); router.push(route); } }
  return <div className="relative ml-auto w-28 sm:w-44 md:ml-0 lg:w-56"><label htmlFor="career-search" className="sr-only">Search careers</label><div className="flex min-h-9 items-center rounded-xl border border-white/[.08] bg-white/[.035] px-3 focus-within:border-indigo-400/60"><svg aria-hidden="true" viewBox="0 0 24 24" className="size-3.5 shrink-0 fill-none stroke-slate-500" strokeWidth="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input ref={inputRef} id="career-search" role="combobox" aria-autocomplete="list" aria-expanded={open && Boolean(query)} aria-controls="career-search-results" value={query} onFocus={() => setOpen(true)} onBlur={() => window.setTimeout(() => setOpen(false), 120)} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} onKeyDown={(event) => { if (event.key === "Escape") { setOpen(false); event.currentTarget.blur(); } if (event.key === "Enter") choose(results[0]?.route); }} placeholder="Search careers..." autoComplete="off" className="min-w-0 flex-1 bg-transparent px-2 py-2 text-xs text-white outline-none placeholder:text-slate-600"/><kbd className="hidden text-[9px] text-slate-600 lg:block">⌘K</kbd></div>{open && query ? <div id="career-search-results" role="listbox" className="absolute inset-x-0 top-[calc(100%+.5rem)] overflow-hidden rounded-xl border border-white/10 bg-[#090b19]/95 p-1 shadow-2xl backdrop-blur-xl">{results.length ? results.map((career) => <button key={career.id} role="option" aria-selected="false" disabled={!career.route} onMouseDown={(event) => event.preventDefault()} onClick={() => choose(career.route)} className="block w-full rounded-lg px-3 py-2 text-left hover:bg-white/[.06] disabled:opacity-45"><span className="block text-xs font-medium text-white">{career.title}</span><span className="text-[10px] text-slate-500">{career.domain}{career.route ? "" : " · Coming soon"}</span></button>) : <p className="px-3 py-4 text-xs text-slate-500">No careers found.</p>}</div> : null}</div>;
}

