"use server";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/admin/adminAuth";
import { createManualSalaryCandidate,publishSalaryCandidate,rejectSalaryCandidate } from "@/lib/admin/manualSalaryRepository";

async function token(){const auth=await requireAdmin();if(auth.status!=="admin")throw new Error("ADMIN_REQUIRED");return auth.accessToken}
function destination(kind:string,message:string){return `/admin/intelligence/manual-salary?${kind}=${encodeURIComponent(message)}`}
export async function createManualSalaryAction(formData:FormData){let next:string;try{const metrics=JSON.parse(String(formData.get("metrics")??"[]"));const value={countryCode:String(formData.get("countryCode")??""),currencyCode:String(formData.get("currencyCode")??""),occupationFamilyId:String(formData.get("occupationFamilyId")??""),occupationMappingId:String(formData.get("occupationMappingId")??""),sourceId:String(formData.get("sourceId")??""),sourceRelease:{providerReleaseId:String(formData.get("providerReleaseId")??""),releaseDate:String(formData.get("releaseDate")??""),referencePeriodStart:String(formData.get("referencePeriodStart")??""),referencePeriodEnd:String(formData.get("referencePeriodEnd")??""),sourceMetadata:{entryMethod:"admin-manual-ui"}},metrics};const candidate=await createManualSalaryCandidate(await token(),value);next=destination("success",`Candidate ${candidate.id.slice(0,8)} is ready for review. Nothing was published.`)}catch(error){next=destination("error",error instanceof SyntaxError?"Salary metrics are malformed.":"Candidate creation failed. Check readiness, source approval, release identity, and metric values.")}redirect(next)}
export async function publishManualSalaryAction(formData:FormData){const id=String(formData.get("candidateId")??"");let next:string;try{await publishSalaryCandidate(await token(),id);next=destination("success","Candidate published successfully.")}catch{next=destination("error","Publication failed safely; published data was not changed.")}redirect(next)}
export async function rejectManualSalaryAction(formData:FormData){const id=String(formData.get("candidateId")??""),reason=String(formData.get("reason")??"");let next:string;try{await rejectSalaryCandidate(await token(),id,reason);next=destination("success","Candidate rejected and retained in audit history.")}catch{next=destination("error","Rejection failed. Enter a reason between 3 and 500 characters.")}redirect(next)}
