import{boundedOfficialFetch}from"../officialFetch.ts";import type{AdapterPlan,AdapterPlanItem,NormalizedObservationDraft,OfficialRefreshSelection,OfficialSourceAdapter,RetrievedRelease}from"../officialSourceAdapter.ts";
export interface BlsOccupationMapping{id:string;socCode:string;title:string;weight:number;mappingVersion:string;reviewStatus:"approved"|"draft"|"rejected"}
interface BlsDatum{year:string;period:string;value:string;footnotes?:Array<{text?:string}>}interface BlsSeries{seriesID:string;data:BlsDatum[]}interface BlsResponse{status:string;Results?:{series?:BlsSeries[]}}
const endpoint="https://api.bls.gov/publicAPI/v2/timeseries/data/";
export function blsMweSeriesId(socCode:string){const occupation=socCode.replace("-","");if(!/^\d{6}$/.test(occupation))throw new Error("INVALID_SOC_CODE");return `WMU0000000102000000${occupation}0000`}
export class BlsMweAdapter implements OfficialSourceAdapter{
 id="bls-mwe";countries=["us"] as const;capabilities=["salary"] as const;private bySeries:Map<string,BlsOccupationMapping>;private mappings:BlsOccupationMapping[];private fetcher:typeof fetch;
 constructor(mappings:BlsOccupationMapping[],fetcher:typeof fetch=fetch){this.mappings=mappings;this.fetcher=fetcher;this.bySeries=new Map(mappings.map(mapping=>[blsMweSeriesId(mapping.socCode),mapping]))}
 async plan(selection:OfficialRefreshSelection):Promise<AdapterPlan>{if(selection.countries.some(country=>country!=="us")||selection.capabilities.some(capability=>capability!=="salary"))throw new Error("BLS_MWE_CAPABILITY_UNSUPPORTED");const pending=this.mappings.filter(mapping=>mapping.reviewStatus!=="approved");return{items:[{sourceSlug:"us-bls-mwe-unapproved",countryCode:"us",capability:"salary",endpoint,requestCount:1,estimatedResponseBytes:Math.max(4096,this.mappings.length*2048),mappingVersion:this.mappings[0]?.mappingVersion??"unmapped",queryDefinitionVersion:selection.queryDefinitionVersion}],totalRequests:1,estimatedResponseBytes:Math.max(4096,this.mappings.length*2048),warnings:pending.length?[`${pending.length} occupation mappings require approval.`]:[]}}
 async retrieve(item:AdapterPlanItem):Promise<RetrievedRelease>{if(this.mappings.some(mapping=>mapping.reviewStatus!=="approved"))throw new Error("OCCUPATION_MAPPING_NOT_APPROVED");const response=await boundedOfficialFetch(item.endpoint,{method:"POST",body:JSON.stringify({seriesid:[...this.bySeries.keys()]}),headers:{"Content-Type":"application/json"}},{allowedOrigins:["https://api.bls.gov"],timeoutMs:15000,maxAttempts:2},this.fetcher),payload=await response.json() as BlsResponse;if(payload.status!=="REQUEST_SUCCEEDED"||!payload.Results?.series?.length)throw new Error("BLS_RESPONSE_INVALID");const years=payload.Results.series.flatMap(series=>series.data.map(value=>Number(value.year))).filter(Number.isFinite),year=Math.max(...years);return{providerReleaseId:`bls-mwe-${year}`,releaseDate:`${year}-12-31`,referencePeriodStart:`${year}-01-01`,referencePeriodEnd:`${year}-12-31`,retrievedAt:new Date().toISOString(),sourceMetadata:{program:"Modeled Wage Estimates",retrievalDisclaimer:"BLS cannot vouch for analyses after retrieval."},records:payload.Results.series}}
 async normalize(item:AdapterPlanItem,release:RetrievedRelease):Promise<NormalizedObservationDraft[]>{const result:NormalizedObservationDraft[]=[];for(const series of release.records as BlsSeries[]){const mapping=this.bySeries.get(series.seriesID),datum=series.data.find(value=>value.period==="A01")??series.data[0],hourly=Number(datum?.value);if(!mapping||!datum||!Number.isFinite(hourly))continue;const common={occupationFamilyId:"10000000-0000-4000-8000-000000000001",occupationMappingId:mapping.id,sourceSlug:item.sourceSlug,sourceReleaseKey:release.providerReleaseId,countryCode:"us",regionCode:null,capability:"salary" as const,periodStart:release.referencePeriodStart,periodEnd:release.referencePeriodEnd,currencyCode:"USD",evidence:{seriesId:series.seriesID,socCode:mapping.socCode,occupationTitle:mapping.title,weight:mapping.weight,footnotes:datum.footnotes??[]},confidence:"moderate" as const,qualityFlags:["occupation-family-proxy"]};result.push({...common,metricCode:"average_hourly_wage",value:hourly,unit:"currency_per_hour",provenance:"source",derivationMethod:null,derivationVersion:null});result.push({...common,metricCode:"annualized_average_wage",value:hourly*2080,unit:"currency_per_year",provenance:"derived",derivationMethod:"hourly wage multiplied by 2,080 hours",derivationVersion:"annualization-1.0.0"})}return result}
}
