import{boundedOfficialFetch}from"../officialFetch.ts";import type{AdapterPlan,AdapterPlanItem,NormalizedObservationDraft,OfficialRefreshSelection,OfficialSourceAdapter,RetrievedRelease}from"../officialSourceAdapter.ts";
export const BLS_OEWS_ENDPOINT="https://api.bls.gov/publicAPI/v2/timeseries/data/";
export const BLS_OEWS_DATATYPE_URL="https://download.bls.gov/pub/time.series/oe/oe.datatype";
export const BLS_OEWS_SOURCE_SLUG="us-bls-oews";
export const BLS_OEWS_APPROVED_SOCS=["15-2051","15-1252","15-1221"]as const;
type OewsCapability="salary"|"employment_count";
export interface BlsOewsOccupationMapping{id:string;socCode:typeof BLS_OEWS_APPROVED_SOCS[number];title:string;mappingVersion:string;reviewStatus:"approved"|"draft"|"rejected"}
interface BlsFootnote{code?:string;text?:string}interface BlsDatum{year:string;period:string;periodName?:string;value:string;footnotes?:BlsFootnote[];releaseDate?:string}interface BlsSeries{seriesID:string;data:BlsDatum[]}interface BlsResponse{status:string;message?:string[];Results?:{series?:BlsSeries[]}}
const dataTypes={employment_count:{"01":{metricCode:"employment_count",unit:"people",currencyCode:null}},salary:{"13":{metricCode:"median_annual_wage",unit:"currency_per_year",currencyCode:"USD"},"08":{metricCode:"median_hourly_wage",unit:"currency_per_hour",currencyCode:"USD"},"04":{metricCode:"mean_annual_wage",unit:"currency_per_year",currencyCode:"USD"},"03":{metricCode:"mean_hourly_wage",unit:"currency_per_hour",currencyCode:"USD"}}}as const;
function capabilityOf(item:AdapterPlanItem):OewsCapability{if(item.capability!=="salary"&&item.capability!=="employment_count")throw new Error("BLS_OEWS_CAPABILITY_UNSUPPORTED");return item.capability}
export function blsOewsSeriesId(socCode:string,dataType:string){const occupation=socCode.replace("-","");if(!BLS_OEWS_APPROVED_SOCS.includes(socCode as typeof BLS_OEWS_APPROVED_SOCS[number])||!/^\d{6}$/.test(occupation)||!/^\d{2}$/.test(dataType))throw new Error("BLS_OEWS_SERIES_UNAPPROVED");return`OEUN0000000000000${occupation}${dataType}`}
function expectedSeries(mappings:BlsOewsOccupationMapping[],capability:OewsCapability){const types=Object.keys(dataTypes[capability]);return new Map(mappings.flatMap(mapping=>types.map(type=>[blsOewsSeriesId(mapping.socCode,type),{mapping,type}]as const)))}
function selectLatestCompleteA01(series:BlsSeries[],expected:Map<string,unknown>){if(series.length!==expected.size)throw new Error("BLS_OEWS_SERIES_SET_MISMATCH");const byId=new Map<string,BlsSeries>();for(const item of series){if(!expected.has(item.seriesID)||byId.has(item.seriesID))throw new Error("BLS_OEWS_SERIES_ID_MISMATCH");byId.set(item.seriesID,item)}const candidateYears=[...new Set(series.flatMap(item=>item.data.filter(datum=>datum.period==="A01"&&/^\d{4}$/.test(datum.year)).map(datum=>Number(datum.year))))].sort((a,b)=>b-a);const year=candidateYears.find(candidate=>[...expected.keys()].every(id=>byId.get(id)?.data.some(datum=>datum.period==="A01"&&Number(datum.year)===candidate)));if(!year)throw new Error("BLS_OEWS_COMPLETE_RELEASE_NOT_FOUND");return{year,records:[...expected.keys()].map(id=>({seriesID:id,data:[byId.get(id)!.data.find(datum=>datum.period==="A01"&&Number(datum.year)===year)!]}))}}
export class BlsOewsAdapter implements OfficialSourceAdapter{
 id="bls-oews";countries=["us"]as const;capabilities=["salary","employment_count"]as const;private mappings:BlsOewsOccupationMapping[];private fetcher:typeof fetch;
 constructor(mappings:BlsOewsOccupationMapping[],fetcher:typeof fetch=fetch){this.mappings=mappings;this.fetcher=fetcher}
 private assertMappingsApproved(){const codes=new Set(this.mappings.map(mapping=>mapping.socCode));if(this.mappings.length!==BLS_OEWS_APPROVED_SOCS.length||BLS_OEWS_APPROVED_SOCS.some(code=>!codes.has(code))||this.mappings.some(mapping=>mapping.reviewStatus!=="approved"))throw new Error("OCCUPATION_MAPPING_NOT_APPROVED")}
 async plan(selection:OfficialRefreshSelection):Promise<AdapterPlan>{if(selection.countries.length!==1||selection.countries[0]!=="us"||selection.capabilities.some(capability=>capability!=="salary"&&capability!=="employment_count"))throw new Error("BLS_OEWS_CAPABILITY_UNSUPPORTED");const capabilities=[...new Set(selection.capabilities)]as OewsCapability[],bytes=Math.max(4096,this.mappings.length*capabilities.length*4096),warnings:string[]=[];try{this.assertMappingsApproved()}catch{warnings.push("All three approved US SOC mappings are required before OEWS retrieval.")}return{items:capabilities.map(capability=>({sourceSlug:BLS_OEWS_SOURCE_SLUG,countryCode:"us",capability,endpoint:BLS_OEWS_ENDPOINT,requestCount:1,estimatedResponseBytes:Math.max(4096,this.mappings.length*4096),mappingVersion:this.mappings[0]?.mappingVersion??"unmapped",queryDefinitionVersion:selection.queryDefinitionVersion})),totalRequests:capabilities.length,estimatedResponseBytes:bytes,warnings}}
 async retrieve(item:AdapterPlanItem):Promise<RetrievedRelease>{this.assertMappingsApproved();const capability=capabilityOf(item),expected=expectedSeries(this.mappings,capability),currentYear=new Date().getUTCFullYear();const response=await boundedOfficialFetch(item.endpoint,{method:"POST",body:JSON.stringify({seriesid:[...expected.keys()],startyear:String(currentYear-9),endyear:String(currentYear)}),headers:{"Content-Type":"application/json"}},{allowedOrigins:["https://api.bls.gov"],timeoutMs:15000,maxAttempts:2},this.fetcher),payload=await response.json()as BlsResponse;if(payload.status!=="REQUEST_SUCCEEDED"||!payload.Results?.series)throw new Error("BLS_OEWS_RESPONSE_INVALID");const selected=selectLatestCompleteA01(payload.Results.series,expected),year=String(selected.year),releaseDates=[...new Set(selected.records.map(series=>series.data[0].releaseDate).filter((value):value is string=>Boolean(value)))];if(releaseDates.length>1)throw new Error("BLS_OEWS_RELEASE_DATE_MISMATCH");return{providerReleaseId:`bls-oews-${year}-a01-national`,releaseDate:releaseDates[0]??null,referencePeriodStart:`${year}-05-01`,referencePeriodEnd:`${year}-05-31`,retrievedAt:new Date().toISOString(),sourceMetadata:{program:"Occupational Employment and Wage Statistics",dataset:`May ${year} National Occupational Employment and Wage Estimates (OEWS national time-series data)`,endpoint:BLS_OEWS_ENDPOINT,datatypeMetadataUrl:BLS_OEWS_DATATYPE_URL,selectedPeriod:"A01",selectedYear:year,retrievalDisclaimer:"BLS cannot vouch for analyses after retrieval."},records:selected.records}}
 async normalize(item:AdapterPlanItem,release:RetrievedRelease):Promise<NormalizedObservationDraft[]>{const capability=capabilityOf(item),metrics=dataTypes[capability]as Record<string,{metricCode:string;unit:string;currencyCode:"USD"|null}>,expected=expectedSeries(this.mappings,capability),result:NormalizedObservationDraft[]=[];for(const series of release.records as BlsSeries[]){const identity=expected.get(series.seriesID);if(!identity)throw new Error("BLS_OEWS_SERIES_ID_MISMATCH");const metric=metrics[identity.type],datum=series.data[0];if(!metric||!datum||datum.period!=="A01")throw new Error("BLS_OEWS_SERIES_ID_MISMATCH");const rawValue=datum.value.trim(),value=Number(rawValue.replaceAll(",",""));if(!rawValue||!Number.isFinite(value))continue;result.push({occupationFamilyId:"10000000-0000-4000-8000-000000000001",occupationMappingId:identity.mapping.id,sourceSlug:item.sourceSlug,sourceReleaseKey:release.providerReleaseId,countryCode:"us",regionCode:null,capability,metricCode:metric.metricCode,periodStart:release.referencePeriodStart,periodEnd:release.referencePeriodEnd,value,unit:metric.unit,currencyCode:metric.currencyCode,provenance:"source",derivationMethod:null,derivationVersion:null,evidence:{seriesId:series.seriesID,socCode:identity.mapping.socCode,occupationTitle:identity.mapping.title,datatypeCode:identity.type,datatypeMetadataUrl:BLS_OEWS_DATATYPE_URL,sourceReportedValue:rawValue,suppressionMarker:null,footnotes:datum.footnotes??[],releaseDate:release.releaseDate,referencePeriod:{start:release.referencePeriodStart,end:release.referencePeriodEnd},sourcePeriod:datum.period,sourceYear:datum.year},confidence:"moderate",qualityFlags:["occupation-family-proxy","separate-soc-observation"]})}return result}
}
