import "server-only";
import { createStructuredAdminResponse } from "@/lib/admin/ai/openaiAdminClient";

export type AssessmentDraftRequest={careerTitle:string;stageTitle:string;assessmentType:"topic"|"comprehensive";topic:string;learningGoals:string[];questionCount:number};
export type AssessmentQuestionDraft={id:string;question:string;answers:string[];correctAnswerIndex:number;explanation:string;difficulty:"Beginner"|"Intermediate"|"Advanced";relatedTopic:string;questionType:"multiple-choice"|"true-false"|"scenario"|"code-interpretation"};
export type AssessmentDraft={title:string;description:string;questions:AssessmentQuestionDraft[];reviewNotes:string[]};

function schema(questionCount:number){return {type:"object",additionalProperties:false,required:["title","description","questions","reviewNotes"],properties:{title:{type:"string"},description:{type:"string"},questions:{type:"array",minItems:questionCount,maxItems:questionCount,items:{type:"object",additionalProperties:false,required:["id","question","answers","correctAnswerIndex","explanation","difficulty","relatedTopic","questionType"],properties:{id:{type:"string"},question:{type:"string"},answers:{type:"array",minItems:2,maxItems:4,items:{type:"string"}},correctAnswerIndex:{type:"integer",minimum:0,maximum:3},explanation:{type:"string"},difficulty:{type:"string",enum:["Beginner","Intermediate","Advanced"]},relatedTopic:{type:"string"},questionType:{type:"string",enum:["multiple-choice","true-false","scenario","code-interpretation"]}}}},reviewNotes:{type:"array",items:{type:"string"}}}} as const}

const instructions=`You are the Career OS Assessment Architect. Create assessment questions only from the supplied Career, stage, topic, and learning goals. Do not invent certifications, salary figures, market statistics, legal claims, product limits, version-specific facts, or details requiring external verification. Prefer conceptual, scenario-based, workflow, decision, and applied-practice questions. Every question must have exactly one unambiguously correct answer. Explanations must teach why the correct answer is correct. Avoid duplicates and superficial paraphrases. This is a human-reviewed draft and must never imply independent verification.`;

export async function generateAssessmentDraft(request:AssessmentDraftRequest){const count=Math.max(5,Math.min(request.questionCount,20));return createStructuredAdminResponse<AssessmentDraft>({name:"career_os_assessment_draft",description:"Human-reviewed Career OS assessment question draft.",schema:schema(count),instructions,input:`Generate a ${request.assessmentType} assessment draft.\n${JSON.stringify({...request,questionCount:count},null,2)}`})}
