import "server-only";
import { supabaseUserFetch } from "@/lib/admin/supabaseServer";
export interface AdminSnapshot{id:string;career_slug:string;country_code:string;snapshot_type:"market"|"salary";provider:string;status:"draft"|"validating"|"published"|"rejected"|"superseded";version:number;query_metadata:Record<string,unknown>;normalized_payload:Record<string,unknown>;sample_size:number;total_count:number|null;currency_code:string|null;captured_at:string;published_at:string|null;created_at:string;validation_result:{valid?:boolean;errors?:string[]};refresh_run_id:string;reviewed_at?:string|null;rejection_reason?:string|null}
export interface AdminRefreshRun{id:string;refresh_type:string;trigger_type:string;status:string;started_at:string;completed_at:string|null;planned_calls:number;completed_calls:number;failed_calls:number;provider:string;requested_sample_size:number;triggered_by:string|null}
export interface AdminRefreshItem{id:string;refresh_run_id:string;career_slug:string;country_code:string;capability:string;status:string;provider:string;request_count:number;error_code:string|null;error_message:string|null;started_at:string;completed_at:string|null;pages_requested:number;records_retrieved:number;unique_records_analyzed:number;candidate_snapshot_id:string|null;attempt_count:number;retry_after:string|null}
async function read<T>(path:string,token:string,init:RequestInit={}){const response=await supabaseUserFetch(`/rest/v1/${path}`,token,{...init,headers:{Prefer:"return=representation",...init.headers}});if(!response.ok)throw new Error("ADMIN_INTELLIGENCE_DATABASE_ERROR");return response.json() as Promise<T>}
export async function listAdminSnapshots(token:string,filters:{career?:string;country?:string;type?:string;provider?:string;status?:string}={}){const query=["select=*","order=created_at.desc","limit=250"];if(filters.career)query.push(`career_slug=eq.${encodeURIComponent(filters.career)}`);if(filters.country)query.push(`country_code=eq.${encodeURIComponent(filters.country)}`);if(filters.type)query.push(`snapshot_type=eq.${filters.type}`);if(filters.provider)query.push(`provider=eq.${filters.provider}`);if(filters.status)query.push(`status=eq.${filters.status}`);return read<AdminSnapshot[]>(`intelligence_snapshots?${query.join("&")}`,token)}
export async function getAdminSnapshot(token:string,id:string){const rows=await read<AdminSnapshot[]>(`intelligence_snapshots?id=eq.${encodeURIComponent(id)}&select=*&limit=1`,token);return rows[0]??null}
export async function currentPublishedFor(token:string,snapshot:AdminSnapshot){const rows=await read<AdminSnapshot[]>(`intelligence_snapshots?career_slug=eq.${encodeURIComponent(snapshot.career_slug)}&country_code=eq.${snapshot.country_code}&snapshot_type=eq.${snapshot.snapshot_type}&status=eq.published&select=*&limit=1`,token);return rows[0]??null}
export async function listRefreshRuns(token:string,limit=50){return read<AdminRefreshRun[]>(`intelligence_refresh_runs?select=*&order=started_at.desc&limit=${limit}`,token)}
export async function getRefreshRun(token:string,id:string){const rows=await read<AdminRefreshRun[]>(`intelligence_refresh_runs?id=eq.${encodeURIComponent(id)}&select=*&limit=1`,token);return rows[0]??null}
export async function listRefreshItems(token:string,runId?:string){return read<AdminRefreshItem[]>(`intelligence_refresh_items?select=*&order=started_at.asc${runId?`&refresh_run_id=eq.${encodeURIComponent(runId)}`:""}`,token)}
export async function snapshotsByIds(token:string,ids:string[]){if(!ids.length)return[];return read<AdminSnapshot[]>(`intelligence_snapshots?id=in.(${ids.map(encodeURIComponent).join(",")})&select=id,status,reviewed_at,rejection_reason,career_slug,country_code,snapshot_type,provider,version,query_metadata,normalized_payload,sample_size,total_count,currency_code,captured_at,published_at,created_at,validation_result,refresh_run_id`,token)}
export async function publishCandidate(token:string,id:string,acknowledgeHighChange=false){return read<AdminSnapshot>("rpc/admin_publish_intelligence_candidate",token,{method:"POST",body:JSON.stringify({p_snapshot_id:id,p_acknowledge_high_change:acknowledgeHighChange})})}
export async function rejectCandidate(token:string,id:string,reason:string){return read<AdminSnapshot>("rpc/admin_reject_intelligence_candidate",token,{method:"POST",body:JSON.stringify({p_snapshot_id:id,p_reason:reason.slice(0,500)})})}
